### ISSUE TITLE
An option (environment variable) to enabled `dotnet watch`

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/s2i-dotnetcore#116]
When creating an application, it would be very handy to have the dotnet image providing an option to use `dotnet watch` automatically so that `oc rsync` would cascade to a live update of the .NET application.

**Comment by tmds** [comment]
The s2i scripts are meant for assembling a published application and executing that published application.
In this case, the application should not be published but run and restarted on code changes.
So unlike the s2i assemble script, this process would never stop.
Note that dotnet watch is not part of the cli, it's a command that needs to be referenced as part of the application project. When there is no such reference, the watch command will fail.

Can you give some example docker commands that show how you want to use the image?

**Comment by mickaelistria** [comment]
Ok, I though `dotnet watch` was doing some live-reload on the running application. But if it's restarting the app, it's indeed very different. It seems like my user story of using RHDS or `oc rsync` on a running ASP.NET pod cannot lead to a live update of the application.
Note that I'm a "Hello world"-level C# developer, OpenShift and Docker user. So I don't have any clue how to make this instant update process work here.

**Comment by mickaelistria** [comment]
If one uses `dotnet watch run` instead of `dotnet run` to start the application, than any change to a .cs file would cascade to a restart of the application (under the same parent process so it remains the same pod).
So I really think that it would be worth adding the ability to use `dotnet watch run` instead of `dotnet run` on OpenShift as it would deliver a very short feedback loop workflow

. edit a .cs file
. `oc rsync` (done automatically on change with Red Hat Developers Studio and its OpenShift server adapter)

And the app is automatically updated.

**Comment by mickaelistria** [comment]
Note that this works for `dotnet watch run`, but `dotnet watch /path/to/project.dll` doesn't update (as it most likely monitor only the content of the dll which isn't changed, nor changeable as it's being used.

So an environemnet variable would replace `dotnet /path/to/project.dll` with `dotnet run watch` and that should be all good to enable high productivity with the `oc rsync` workflow and RHDS.

**Comment by jerboaa** [comment]
@mickaelistria I suggest to prototype this by overriding s2i/assemble and/or s2i/run in your application. Example: https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/dotnetcore-1.0/app/.s2i/bin/run

You can see our current 2.0 assemble and run scripts here:
https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/s2i/bin

This would allow us to see exactly what's needed.

**Comment by mickaelistria** [comment]
The permission issue (#114) is currently a blocker before I can try this.

**Comment by tmds** [comment]
I don't think the `assemble` script and `run` script can be used to implement a watch feature.
`assemble` is supposed to be a finite operation. `run` is supposed to run until you kill it to replace it. watch is neither of those.

**Comment by mickaelistria** [comment]
The assemble should be changed, it would still be a `dotnet publish`
The run could be a `dotnet watch run`, which runs (like `dotnet run` or
`dotnet exec`) until we kill it and watch for changes at the same time.
Unless I'm missing something, my local experiments show that `dotnet watch
run` can be a good substitute in dev mode for `dotnet /path/to/project.dll`.

**Comment by tmds** [comment]
`dotnet publish` is slow, it copies all referenced assemblies.
`dotnet run` is not used on published folders, it's for development.

> my local experiments show that `dotnet watch
run` can be a good substitute in dev mode for `dotnet /path/to/project.dll`.

That is what it is for. (note: `dotnet run` rebuilds when sources have changed.)
So if you put `dotnet watch run` in the s2i `run` script, that will rebuild&run on changes. The application that is generated in the `assemble` script is not used.

This overrides everything these scripts are doing. We shouldn't touch the s2i scripts for this unless you are bound to those scripts. If you are not, it's cleaner to use the image as a generic sdk, so you can `exec dotnet run` into it. Or we can consider to add a `watch` script that supports some of the `assemble` envvars.

**Comment by mickaelistria** [comment]
Ok. So it seems to me that this would rather be a different image then: something like `dotnet-devel` which would do only `dotnet restore` in the assemble script and `dotnet run` or `dotnet watch run` in the run script.

The thing is that if we want some good workflows that compare with nodejs or even Java EE apps for example, we need the simplest way to have this auto-refresh from Red Hat Developer Studio to .NET on OpenShift working. `dotnet watch run` seems to be the only viable solution as none of the other `dotnet watch` commands seems to monitor the whole project folder. If `dotnet watch run` makes `dotnet publish` useless, the differences with the current `dotnet` image are getting very big, hence why I think a dedicated image could be better to support this workflow properly.
WDYT?

**Comment by tmds** [comment]
I think you should do some proto-typing :smile: 

I think RHDS is limiting if mandates using the `assemble` and `run` scripts. Suppose that is the case, how do you tell it it shouldn't kill the `run` script when it wants to do a new `assemble`.

Also you need to work out where the watch package is coming from. What if the user doesn't reference this in his project? Is there a fall-back?
How does watch work in a multi-project solution? Are there some issues when running watch in a container? ...

I'd rather 'pollute' the s2i scripts than have a dedicated image for this use-case. Preferably this can all be done without touching the s2i scripts.

**Comment by mickaelistria** [comment]
So I'm locally tweaking the .s2i/bin scripts in my project Git repo. The `assemble` one (doing only `dotnet restore`) seems OK, the `run` one (doing `dotnet watch`) sends the following error
> System.AggregateException: One or more errors occurred. (Unable to obtain lock file access on '/tmp/NuGetScratch/lock/c89eaa0199c070547c05224962ee2ca24b5337bf' for operations on '/opt/app-root/.nuget/packages/.tools/microsoft.visualstudio.web.codegeneration.tools/2.0.0/netcoreapp2.0/project.assets.json'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/c89eaa0199c070547c05224962ee2ca24b5337bf' will allow NuGet to continue.) ---> System.InvalidOperationException: Unable to obtain lock file access on '/tmp/NuGetScratch/lock/c89eaa0199c070547c05224962ee2ca24b5337bf' for operations on '/opt/app-root/.nuget/packages/.tools/microsoft.visualstudio.web.codegeneration.tools/2.0.0/netcoreapp2.0/project.assets.json'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/c89eaa0199c070547c05224962ee2ca24b5337bf' will allow NuGet to continue.

How could I avoid that?

**Comment by tmds** [comment]
`dotnet restore` creates lock files under tmp to ensure no 2 processes are trying to restore the same package. Probably `dotnet watch` is killing `dotnet run` during a packet restore leaving the lock files under tmp. Try including `rm -rf /tmp/NuGetScratch` in your `dotnet watch` command.

**Comment by mickaelistria** [comment]
Ok, I created
a `.s2i/bin/assemble` file
```
echo "---> Copying application source ..."
cp -Rf /tmp/src/. ./
echo "---> Restore"
dotnet restore $DOTNET_STARTUP_PROJECT

echo "---> Fix permissions"
# Fix source directory permissions
fix-permissions ./
# set permissions for any installed artifacts
fix-permissions /opt/app-root
```
and a `.s2i/bin/run` file
```
rm -rf /tmp/NuGetScratch
dotnet watch run
```
And the application seems to start as expected.

However, now, I'm back to permissions issue that I believe are caused by #118 (tar-based sync complains about files not being writable where rsync would simply not touch unmodified files)

**Comment by tmds** [comment]
Probably you also want to pick up package changes in the csproj file, so you may want to: `dotnet watch rm -rf /tmp/NuGetScratch && dotnet restore && dotnet run`.

> tar-based sync complains about files not being writable where rsync would simply not touch unmodified files

:confused: rsync would still be updating the modified files, so why wouldn't those have a permission issue?

**Comment by mickaelistria** [comment]
> rsync would still be updating the modified files, so why wouldn't those have a permission issue?

I believe the file isn't actually modified (it's a git hash). `tar` doesn't check for equality before trying to expand the archive, so even for unmodified files, it fails when permissions don't allow that. I expect `rsync` to nt try to write unmodified files and then fail less... I admit it's just a bet more that a conviction ;)

**Comment by tmds** [comment]
The jboss openshift server plugin uses some labels of the image, e.g. nodejs:

```
      com.redhat.dev-mode="DEV_MODE:false" \
      com.redhat.deployments-dir="/opt/app-root/src" \
      com.redhat.dev-mode.port="DEBUG_PORT:5858" \
      com.redhat.component="rh-nodejs6-docker" \
```

The `com.redhat.dev-mode` describes the envvar that must be set to change the s2i script behavior. For the nodejs image the behavior is described as:

> When set to "true", nodemon will be used to automatically reload the server while you work (default: "false"). Setting DEV_MODE to "true" will change the NODE_ENV default to "development" (if not explicitly set).

**Comment by tmds** [comment]
I'm looking a bit at the dotnet watch implementation, and there are some pitfalls:
- only handles 1 project. (that project can reference other projects.)
- doesn't detect new files. (It inspects the project and then monitors all the files in the project, but it doesn't see when new files are added.)

Since we have nodejs in our image, I think we are better off using nodemon instead.

**Comment by tmds** [comment]
Implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/123
