### ISSUE TITLE
Add rsync to dotnet/dotnet-20-rhel7

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/s2i-dotnetcore#118]
In order to better support the `oc rsync` command (which happens to be faster than alternatives commands to push a snapshot to running pod), it would be good to include in the image the `rsync` executable, or to inherit from an image that already has rsync.

**Comment by tmds** [comment]
What's the use-case? If this is for copying code into the container, the following `dotnet restore` and `dotnet build` steps will make the rsync perf gain unobservable.

**Comment by mickaelistria** [comment]
The use case is from Red Hat Developer Studio, I edit a .cs file locally for a .NET application deployed and running on OpenShift. I would like this modified .cs file to automatically be available on the running pods of the application so the .NET application can react to changes.. Red Hat Developer Studio does that by calling `oc rsync` on change.
`oc rsync` has a failback mode IIRC, but it's not as performant. Having rsync installed would speed up synchronization of the local source code with what's deployed on OpenShift (without pushing a commit nor restarting a build).

**Comment by tmds** [comment]
I'm sure it will be faster. It would be nice to know how much faster it is and if that is significant in the overall use-case. Even without the numbers, we can make the change. It's simple and dotnet-20-rhel7 isn't a tiny image.

**Comment by aslicerh** [comment]
Ok, rsync has been merged in from #119 to both the runtime and the build images, so I'm closing this.
