### ISSUE TITLE
[Proposal] DEV_MODE: support publishing

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#124]
As enhancement, it may be interesting for the user to be able to publish instead of run the application.

Note that the current behavior (run) is similar to the VS IDE user experience.
publish is intended for packing the application and involves steps that make it slower than run.
The normal s2i build in OpenShift publishes the application.

CC @mickaelistria

**Comment by mickaelistria** [comment]
The DEV_MODE already seems relatively slow (~15s between a save in the IDE and page update in the browser). We should avoid everything that risks making it slower unless it shows clear value.
As a non-.NET developer, I don't know the value of publishing in a dev mode with fast feedback loop.
cc @rgrunber

**Comment by tmds** [comment]
I wouldn't make this the default. It may be interesting as an option since the default OpenShift build executes a published application.

**Comment by tmds** [comment]
I've added Proposal to the title. We won't implement this unless someone endorses the feature.

**Comment by tmds** [comment]
Closing. We can re-open if there is interest.
