### ISSUE TITLE
Support building top level .sln files

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore#128]
I received a few requests from customers about wanting to use our s2i images with `.sln` (solution) files. I cant tell if it those are supported for s2i or not. We should document it if it is already implemented or implement it if it missing.

I believe their use case looks like this:

    Main.sln
    ├── Project1
    │   ├── Project1.csproj
    │   └── Program.cs
    └── Library
        ├── Class1.cs
        └── Library.csproj

It would be great if we could automatically see the `.sln` file and run
an appropriate `dotnet build Main.sln` instead of failing because no
`.csproj` file exists in the directory root.

**Comment by omajid** [comment]
@DonSchenck

**Comment by tmds** [comment]
sln files are currently not supported because they don't store what project is the startup project.
They are a list of projects, mostly used as a way to be opened up together in an IDE.
The dotnet cli doesn't know how to 'publish' or 'run' a solution file.

**Comment by tmds** [comment]
Also, we do support multi-project solutions. It requires the user to indicate the startup project using the DOTNET_STARTUP_PROJECT envvar.
So this feature is a usability improvement which would eliminate the step of adding an '.s2i/environment' file and set the DOTNET_STARTUP_PROJECT in there.

If we add this, I think we can ignore the sln file and recursively search all project files. We'd then have to inspect them (read the xml) and figure out which is the startup project.
We can then also read the AssemblyName to eliminate DOTNET_ASSEMBLY_NAME.
For implementation, we could do the project selection using a .net based app we put in the image. This avoids having to deal with xml in bash.

**Comment by omajid** [comment]
Maybe it would be better to document (with examples) how to make .sln files work by setting the right environment variables? Something like a step by step guide: set `VAR1` to this value, `VAR2` to that value to use `.sln` files.

**Comment by tmds** [comment]
Discussed this with @omajid . We'll improve the assemble script, so when it doesn't find a project, it will output instructions on how to to add an `.s2i/environment` file and list what DOTNET_STARTUP_PROJECTs a user could set.

**Comment by omajid** [comment]
I think we can close this now?

**Comment by tmds** [comment]
Yes we can :) Implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/131.

**Comment by tmds** [comment]
Yes we can :) Implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/131.
