### ISSUE TITLE
image dotnet/dotnet-20-rhel7:latest not found

### ISSUE THREAD

**Issue by wangchong666** [redhat-developer/s2i-dotnetcore#132]
> ./s2i build git://github.com/redhat-developer/s2i-dotnetcore --context-dir=2.0/test/asp-net-hello-world dotnet/dotnet-20-rhel7 dotnet-sample-app

> pulling image error : Error: image dotnet/dotnet-20-rhel7:latest not found
ERROR: An error occurred: unable to get dotnet/dotnet-20-rhel7:latest
ERROR: Suggested solution: check image name, or if using local image add --pull-policy=never flag
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3

>

**Comment by jerboaa** [comment]
@wangchong666 Could it be that your default registry is *not* `registry.access.redhat.com`? Try this:

     $ s2i build git://github.com/redhat-developer/s2i-dotnetcore --context-dir=2.0/test/asp-net-hello-world registry.access.redhat.com/dotnet/dotnet-20-rhel7 dotnet-sample-app

Alternatively pull it from `registry.access.redhat.com` and tag it locally as `dotnet/dotnet-20-rhel7`

**Comment by jerboaa** [comment]
I'm closing this issue assuming my answer fixed your problem. If not, please let us know.
