### ISSUE TITLE
HTTP_PROXY envvar not used by .NET Core

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#140]
.NET Core uses libcurl. libcurl picks up http_proxy (lower-case) but not HTTP_PROXY (upper-case). For other proxy envvars (e.g. HTTPS_PROXY), both the lower and upper case are used.

libcurl: https://github.com/curl/curl/blob/2de63ab179eb78630ee039ad94fb2a5423df522d/lib/url.c#L5203-L5214

**Comment by jerboaa** [comment]
@tmds I don't get it. Curl sources seem to suggest it's using `HTTP_PROXY` (the upper case variant of `http_proxy`) iff `http_proxy` is not set.
https://github.com/curl/curl/blob/2de63ab179eb78630ee039ad94fb2a5423df522d/lib/url.c#L5217
https://github.com/curl/curl/blob/2de63ab179eb78630ee039ad94fb2a5423df522d/lib/url.c#L5185

Thoughts?

**Comment by tmds** [comment]
@jerboaa it is trying uppercase for all things (e.g. all_proxy, https_proxy) except for http_proxy,
```
  /*
   * We don't try the uppercase version of HTTP_PROXY because of
   * security reasons:
   *
   * When curl is used in a webserver application
   * environment (cgi or php), this environment variable can
   * be controlled by the web server user by setting the
   * http header 'Proxy:' to some value.
   *
   * This can cause 'internal' http/ftp requests to be
   * arbitrarily redirected by any external attacker.
   */
  if(!prox && !strcasecompare("http_proxy", proxy_env)) {
    /* There was no lowercase variable, try the uppercase version: */
    Curl_strntoupper(proxy_env, proxy_env, sizeof(proxy_env));
    prox = curl_getenv(proxy_env);
  }
```

**Comment by jerboaa** [comment]
Right, sorry. I somehow read the `!strcasecompare()` condition wrong. Makes sense now. Thanks.
