### ISSUE TITLE
Build failed when Creating  dotnet 1.0 and 1.1 build

### ISSUE THREAD

**Issue by wewang58** [redhat-developer/s2i-dotnetcore#143]
when creating build with
$oc new-build https://github.com/redhat-developer/s2i-dotnetcore --context-
dir=1.0/test/asp-net-hello-world/ ,it displays as "error: DOTNET_STARTUP_PROJECT has no project file
		You can specify the startup project by adding an '.s2i/environment' file to the source repository.
		The source repository has no project files.
		error: build error: non-zero (13) exit code from registry....dca780475373a34be07877b152f94ff7ef4168758f1f9011bc71793245f"
I am not sure if the repo can be used now? hope your feedback

**Comment by wewang58** [comment]
btw, dotnet 2.0 works for the repo

**Comment by wewang58** [comment]
@jerboaa when detail image version dotnet:1.0 : oc new-build dotnet:1.0~https://github.com/redhat-developer/s2i-dotnetcore --context-dir=1.0/test/asp-net-hello-world
build is complete ,thankss very much ,will close the issue

**Comment by jerboaa** [comment]
Glad it worked out.

**Comment by manjerekarrao** [comment]
how to add '.s2i/environment' file to the source repository. i'm actually confused.
or is there a way to add this file to the openshift web console.
