### ISSUE TITLE
Support passing source control info to dotnet build

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#144]
There is a design proposal for passing source control info to dotnet build via environment variables: https://github.com/dotnet/designs/pull/19

This issue tracks adding support for those environment variables to s2i-dotnetcore.

With the current proposal we can map as follows (from https://github.com/dotnet/designs/pull/19#issuecomment-342081006).
```
REPOSITORYCOMMITID = OPENSHIFT_BUILD_COMMIT
REPOSITORYNAME = N/A
REPOSITORYROOT = /opt/app-root/src
REPOSITORYURI = OPENSHIFT_BUILD_SOURCE

The s2i context-dir isn't available as an envvar. So if that is set, the source mapping in the repo is wrong. A user should set DOTNET_STARTUP_PROJECT instead.
```

CC @omajid @jerboaa @aslicerh

**Comment by omajid** [comment]
Hey, did anything happen with this issue?

Is there any support currently for pushing the git commit id into the build? If not, is there some way I can do that manually? For example, on the CLI I can do `dotnet build -p:SourceRevisionId=$$(git rev-parse HEAD`, but there's no way to run such generic commands as part of s2i build, is there?

**Comment by tmds** [comment]
> did anything happen with this issue?

No. This is an old issue and I don't know if .NET is doing something meaningful with these environment variables.
I'm fine closing this, unless someone else wants to look at it further.

Note that `s2i` will add some labels to the image related to the source repository (like `io.openshift.build.commit.id`, and `io.openshift.build.source-location`).

**Comment by omajid** [comment]
> No. This is an old issue and I don't know if .NET is doing something meaningful with these environment variables.

Kind of: [sourcelink uses it to initialize SourceRevisionId](https://github.com/dotnet/sourcelink/blob/4b584dbc392bb1aad49c2eb1ab84d8b489b6dccc/src/Microsoft.Build.StandardCI/build/Microsoft.Build.StandardCI.props), which becomes part of `AssemblyInformationalVersionAttribute`, but you can just leave the env var out and rely on sourcelink to get it automatically from the git repo.

> Note that s2i will add some labels to the image related to the source repository (like io.openshift.build.commit.id, and io.openshift.build.source-location).

Are any of these available at runtime to the application itself?

**Comment by tmds** [comment]
The packages that come with sourcelink should be able to extract this info: https://github.com/dotnet/sourcelink/tree/main/src.
Something like https://github.com/GitTools/GitVersion can be used to embed some of the git metadata in the assembly.

I'm closing this with no further action in s2i-dotnetcore.
