### ISSUE TITLE
Add a test to check runtime version for the 2.0 sdk container

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore#150]
The current 2.0 sdk container tests check the sdk version (`dotnet --version`), but not the runtime version. We should add a test to make sure the sdk container has the right runtime version too to avoid accidental version changes.

**Comment by tmds** [comment]
I'm fine with adding an explicit check.
We are _implicitly_ checking this because the sdk won't run if the runtime does not meet the expected version. That is: sdk 2.0.3 doesn't run on runtime 2.0.0.

**Comment by omajid** [comment]
> That is: sdk 2.0.3 doesn't run on runtime 2.0.0.

Thanks, I didn't know that. Do you know how to identify such implicit dependencies?

**Comment by tmds** [comment]
> Do you know how to identify such implicit dependencies?

The runtime dependency is in the version attribute of the runtime.config file. The runtime can be a later version (roll-forward), but not an earlier version (roll backward).

```
$ find . -name '*.runtimeconfig.json' | xargs grep version
./sdk/2.0.3/dotnet.runtimeconfig.json:      "version": "2.0.3"
./sdk/2.0.3/FSharp/fsc.runtimeconfig.json:      "version": "2.0.3"
./sdk/2.0.3/NuGet.CommandLine.XPlat.runtimeconfig.json:      "version": "2.0.3"
./sdk/2.0.3/Roslyn/csc.runtimeconfig.json:      "version": "2.0.3"
./sdk/2.0.3/Roslyn/vbc.runtimeconfig.json:      "version": "2.0.3"
./sdk/2.0.3/vstest.console.runtimeconfig.json:      "version": "2.0.3"
./sdk/2.0.3/datacollector.runtimeconfig.json:      "version": "2.0.0-beta-001737-00"
./sdk/2.0.3/MSBuild.runtimeconfig.json:      "version": "2.0.3"
```
