### ISSUE TITLE
.NET Core imagestreams not OpenShift Origin 3.7 compatible?

### ISSUE THREAD

**Issue by jerboaa** [redhat-developer/s2i-dotnetcore#155]
In light of https://github.com/redhat-developer/s2i-dotnetcore-ex/issues/33 I'm not sure whether ImageStreams in our repository are 3.7 compatible. See:
https://github.com/openshift/origin/issues/17852

**Comment by jerboaa** [comment]
Also related: https://bugzilla.redhat.com/show_bug.cgi?id=1527638

So far looks like an OpenShift regression.

**Comment by tmds** [comment]
The referenced bugs have been closed/fixed.
