### ISSUE TITLE
Pre-release versions of .Net core?

### ISSUE THREAD

**Issue by TheMidgardWatcher** [redhat-developer/s2i-dotnetcore#158]
Hi there, I have a question regarding nightly builds of Core SDK.

Is it possible to get your images with core 2.1-preview SDK's? 
Or maybe I could use somehow microsoft/dotnet-nightly:2.1 stream?

**Comment by TheMidgardWatcher** [comment]
Any information on this?

**Comment by tmds** [comment]
@TheMidgardWatcher unfortunately we cannot provide daily builds for .NET Core. The upstream project doesn't allow to be built completely by non-Microsoft on a daily basis. When that becomes possible, we can look into providing daily builds.

**Comment by tmds** [comment]
I'm closing this as it is not actionable at this time. When it is feasible to provide daily/preview builds we will work on it.
