### ISSUE TITLE
DOTNET_CONFIGURATION

### ISSUE THREAD

**Issue by Dissimilis** [redhat-developer/s2i-dotnetcore#159]
Readme states:

> DOTNET_CONFIGURATION
> 
> Used to run the application in Debug or Release mode. This should be either Release or Debug. This is passed to the dotnet publish invocation. Defaults to Release.

Why it is suggesting that only possible values are Release and Debug?
I think you should update this to reflect, that custom configurations also can be passed.

Possible correction:
> Used to build/run the application in specified configuration mode (i.e.  Debug, Release). This is passed to the dotnet publish and dotnet run invocation as `-c` paremeter. Defaults to Release.

**Comment by tmds** [comment]
The cli documentation also suggests to use the these values. afaik there are no other values with predefined semantics and it is not common to use other values. We don't prohibit setting it to something different.
