### ISSUE TITLE
Define the profile to use

### ISSUE THREAD

**Issue by unix1982** [redhat-developer/s2i-dotnetcore#160]
Hi I have seen that I can pass some Environment variable in the buildconfig (example DOTNET_STARTUP_PROJECT). So I'm looking for a possibility to add the '--launch-profile' that I use lockally in visual studio code or visual studio to define the environment where I run it. Is there a possibility? (I think more correct is to set this in the deploy config)

**Comment by omajid** [comment]
Do you mean environments like `Production`, `Development` and `Staging`? You can set these via the environment variable [`ASPNETCORE_ENVIRONMENT`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments). 

If you are using OpenShift, the right way to use those would be via the Deployment Configuration.

One possible way to do that would be to set it via `oc new-app`:

    oc new-app -e ASPNETCORE_ENVIRONMENT=Staging [rest of your regular arguments]

Or, if you are using the web interface, look for the "Environment Variables" under "Deployment Configuration" when you are creating the application.

**Comment by tmds** [comment]
The launch-profiles are a development feature. They contain a number of environment variables and tell the IDE what url to open.
During deployment, it is recommended to use the ASPNETCORE_ENVIRONMENT (see doc referenced by @omajid ).
