### ISSUE TITLE
Incorporate new environment variables used by official .NET Core containers

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore#163]
The Microsoft containers recently introduced 3 new environment variables in some containers: https://github.com/dotnet/dotnet-docker/pull/428.

We should look into adapting those to make it easier for users to switch from one set of containers to the other.

**Comment by tmds** [comment]
> ENV DOTNET_USE_POLLING_FILE_WATCHER true

This is needed to make the `dotnet watch` command work.
I guess this is to enable a scenario similar to devmode with VS.
We could set this, but we don't have a scenario that needs this, and we don't know if it enables using our images in the Microsoft scenario.

> ASPNETCORE_URLS=http://+:80

We are setting this to `ASPNETCORE_URLS=http://*:8080`. 8080 is the port of our container. I don't know what the difference is between '+' and '*'. The docs only mentions '*': https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#server-urls.

> DOTNET_RUNNING_IN_CONTAINER

This variable is not on the master branch. I think it was to enable part of the devmode scenario. It's not part of any docs.

**Comment by tmds** [comment]
> I don't know what the difference is between '+' and '*'

It seems they are the same thing.

https://github.com/aspnet/KestrelHttpServer/blob/dfaf37cbba684a9913b79ec68fdf5ad18378c170/src/Kestrel.Core/Internal/AddressBinder.cs#L149

So let's stick to the documented format.

**Comment by tmds** [comment]
@omajid fyi, this is being discussed in https://github.com/dotnet/dotnet-docker/issues/432
