### ISSUE TITLE
Diff imagestreams and templates with openshift/openshift-ansible and openshift/origin

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#168]
The imagestreams and templates from this repos are copied to the openshift/openshift-ansible and openshift/origin repos.

We need to check these files are the same.
And it would be good to have a CI job that detects when they are no longer in sync.

CC @omajid @aslicerh @RheaAyase

**Comment by aslicerh** [comment]
I was looking at this earlier, and it looks like ansible creates it's example repos from a script that grabs the newest imagestream files directly from here.

See: https://github.com/openshift/openshift-ansible/blob/2af1f4992c52559015297562f9dc897821f0488c/roles/openshift_examples/examples-sync.sh#L45

So, I don't know if it is necessary to check the files there.


- - - - -

The openshift origin one is probably valid to check. 

I also found imagestreams in openshift/library. Those are also 'auto-pulled' by a script, but unlike the ansible stuff above, the library stuff seems to only keep one version around, not 'packs' of version numbered examples.

I was thinking about creating a python script to put into the base of s2i-dotnetcore to just md5 these things. We could then use that as a jenkins job to check for this stuff.

Thoughts?

**Comment by tmds** [comment]
@aslicerh see this comment: https://github.com/openshift/library/pull/68#issuecomment-377533964

**Comment by tmds** [comment]
From chatting with @jerboaa I learned that updates of openshift/openshift-ansible go through a RHBZ workflow. After a ticket is created, OpenShift qa does verification. Once that is ok, Scott Dodson is asked via mail to update those files.
For openshift/origin, we are responsible for keeping things in sync.

**Comment by tmds** [comment]
https://github.com/openshift/origin/pull/19367 adds our templates to origin.

**Comment by tmds** [comment]
> I was thinking about creating a python script to put into the base of s2i-dotnetcore to just md5 these things. We could then use that as a jenkins job to check for this stuff.

This is the remaining action for this issue. I personally prefer a simple bash script. And perhaps we can call 'diff' to visually show differences between the files.

**Comment by tmds** [comment]
We don't need to do anything for this. Those projects are pulling our files.
