### ISSUE TITLE
Automate imagestream testing

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#171]
Our tests are docker and image centric.
It would be nice to also automate testing of imagestreams/templates.
Perhaps we can use `minishift` to facilitate running these tests locally.

CC @RheaAyase @aslicerh

**Comment by omajid** [comment]
I think a reasonable first attempt could even ask users to provide an openshift instance that the tests can then run against.

**Comment by tmds** [comment]
Since we're no longer updating templates, we only need to test imagestreams.

**Comment by omajid** [comment]
I am going to close this since https://github.com/redhat-developer/s2i-dotnetcore/pull/310 mostly fixes this and the rest of the work is tracked by https://github.com/redhat-developer/s2i-dotnetcore/issues/313
