### ISSUE TITLE
Nr of ports exposed by image

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#19]
Q: why are we exposing 2 ports?

**Comment by jerboaa** [comment]
Technical debt? I'm not sure we still need it, but the original idea was one TLS enabled port, one plain.

**Comment by tmds** [comment]
Typically ssl termination will happen before the docker container.
I don't know if it does any harm. According to [this blog post](https://sosedoff.com/2016/10/05/docker-gotchas.htm) it's not a good idea to expose unused ports.
Can we pay off the technical debt or is there a reason to keep the port?

**Comment by jerboaa** [comment]
We can remove the port.
