### ISSUE TITLE
Add support for libraries published to nuget

### ISSUE THREAD

**Issue by huntwords** [redhat-developer/s2i-dotnetcore#191]
The current implementation handles applications only.

I would like to be able to build and package library projects (<Project Sdk="Microsoft.NET.Sdk">).

I would also like to push the result to NuGet (using a secret for the API key?).

I suppose some companies may need to push to a private NuGet repository. The repository should be a parameter as well with https://api.nuget.org/v3/index.json as the default value.

**Comment by tmds** [comment]
hi @huntwords the s2i is meant for source-to-image, so the output is an image.

If you want, you can create a custom `.s2i/bin/assemble` file in your repository. In this file you can override the build steps, and for example pack up a library and push it to a server.
OpenShift will still generate an image as end-artifact of the build. In your case it could be an empty image which you ignore.

Alternatively, you may want to use Jenkins on OpenShift which also supports .NET Core.

I'm going to close this as it is not an s2i use-case.

**Comment by huntwords** [comment]
I realize I could override the assemble script. But that becomes a
maintenance problem.

My dept. will eventually have hundreds of these.

Please reconsider. It is a very valid use case. I am surprised you
dismissed it so quickly.

I do understand that the output is not a Docker image. But if s2i works for
us we will want to adopt it for everything for consistency's sake.

If you have ever worked with offshore developers you will understand why.

Thanks anyway.

-k

**Comment by tmds** [comment]
If you want to do this using the s2i builder, you can avoid duplication of the scripts by using the `scripts` property in the build config: https://docs.openshift.com/container-platform/3.9/dev_guide/builds/build_strategies.html#override-builder-image-scripts.
