### ISSUE TITLE
Default DOTNET_NPM_TOOLS to empty in template

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#192]
Since 1.0 we are defaulting DOTNET_NPM_TOOLS to "bower gulp". This were necessary dependencies to publish the default template.
Since 2.0, the .NET Core templates no longer have these dependencies.

I'd like to reset the default value to empty. This avoids wasting time for downloading these unused npm tools.

We need to ensure what we have in our docs keeps working:
```
$ oc new-app --template dotnet-example \
-p DOTNET_IMAGE_STREAM_TAG=dotnet:1.0 \
-p SOURCE_REPOSITORY_REF=dotnetcore-1.0
```
Unfortunately, it is not as simple as adding DOTNET_NPM_TOOLS to an .s2i/environment file in the repo. From what I see, the build environment config (which we would default to empty), takes precedence.
So to deal with this, we'd need to add a custom 'assemble' script to the s2i-dotnetcore-ex 1.0 and 1.1 branch to install the node tools.

@jerboaa @aslicerh @omajid wdyt about this proposed change?

**Comment by jerboaa** [comment]
Have you considered removing DOTNET_NPM_TOOLS from the template and then rely on the user to have a .s2i/environment file if they used `DOTNET_NPM_TOOLS`? Would that work?

**Comment by jerboaa** [comment]
Feel free to go with what you think is best.

**Comment by tmds** [comment]
Fixed in https://github.com/redhat-developer/s2i-dotnetcore/pull/193. Thanks for your input @jerboaa !
