### ISSUE TITLE
Make it easy to trust ca certificates from a number of directories

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#194]
.NET Core 2.1 allows providing ca certificates using SSL_CERT_DIR/SSL_CERT_FILE.

A user may want to combine several ca certificates:
- default certificates provided by the base image
- OpenShift certificates (e.g. /var/run/secrets/kubernetes.io/serviceaccount)
- corporate certificates (e.g. used for on-prem nuget server)

To make it convenient for user to combine multiple locations, we could add support for this using an environment variable (e.g. DOTNET_CERT_DIRS) which can be set to a list of directories.

**Comment by tmds** [comment]
Implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/199

**Comment by HP-dufeng** [comment]
@tmds 
Hi, I use your test project certificatecount,
First : I use below command, output is: **#Certificates: 153**
```
s2i build . registry.access.redhat.com/dotnet/dotnet-21-rhel7 certificatecount

docker run --rm certificatecount
```
Second : I use below command with **DOTNET_CERT_DIRS** env, 
              but the output is still going to be: **#Certificates: 153**,
              expected result should be:  **#Certificates: 154**,
              DOTNET_CERT_DIRS env doesn't seem to work.
```
s2i build . -e DOTNET_CERT_DIRS=certdir1 registry.access.redhat.com/dotnet/dotnet-21-rhel7 certificatecount

docker run --rm certificatecount
```
