### ISSUE TITLE
Trim packages from nodejs

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#197]
We add nodejs to our images for front-end development.
The nodejs package brings a lot of stuff including a c++ compiler and kernel-headers.
We should look at excluding those bits, since they are not important for front-end development.
This will reduce the size of our image and reduce the need to respin our images for CVEs.

**Comment by tmds** [comment]
CC @omajid @aslicerh

**Comment by omajid** [comment]
Doesn't seem like it's easily doable:

    [omajid@rhel7-server ~]$ rpm -q --whatrequires kernel-headers
    glibc-headers-2.17-222.el7.x86_64
    libdrm-devel-2.4.83-2.el7.x86_64
    [omajid@rhel7-server ~]$ rpm -q --whatrequires glibc-headers
    glibc-devel-2.17-222.el7.x86_64
    [omajid@rhel7-server ~]$ rpm -q --whatrequires glibc-devel
    perl-devel-5.16.3-292.el7.x86_64
    gcc-4.8.5-28.el7_5.1.x86_64
    [omajid@rhel7-server ~]$ rpm -q --whatrequires gcc
    gcc-c++-4.8.5-28.el7_5.1.x86_64
    [omajid@rhel7-server ~]$ rpm -q --whatrequires gcc-c++
    rh-nodejs6-node-gyp-3.4.0-5.el7.noarch
    [omajid@rhel7-server ~]$ sudo rpm -e rh-nodejs6-node-gyp
    error: Failed dependencies:
        rh-nodejs6-npm(node-gyp) is needed by (installed) rh-nodejs6-npm-3.10.9-2.el7.noarch
    [omajid@rhel7-server ~]$ sudo yum remove rh-nodejs6-node-gyp
    Loaded plugins: product-id, search-disabled-repos, subscription-manager
    Resolving Dependencies
    --> Running transaction check
    ---> Package rh-nodejs6-node-gyp.noarch 0:3.4.0-5.el7 will be erased
    --> Processing Dependency: rh-nodejs6-npm(node-gyp) for package: rh-nodejs6-npm-3.10.9-2.el7.noarch
    --> Running transaction check
    ---> Package rh-nodejs6-npm.noarch 0:3.10.9-2.el7 will be erased
    --> Processing Dependency: rh-nodejs6-npm for package: rh-nodejs6-2.4-5.el7.x86_64
    --> Running transaction check
    ---> Package rh-nodejs6.x86_64 0:2.4-5.el7 will be erased
    --> Finished Dependency Resolution

    Dependencies Resolved

    =====================================================================================================================
    Package                        Arch              Version                 Repository                            Size
    =====================================================================================================================
    Removing:
    rh-nodejs6-node-gyp            noarch            3.4.0-5.el7             @rhel-server-rhscl-7-rpms             73 k
    Removing for dependencies:
    rh-nodejs6                     x86_64            2.4-5.el7               @rhel-server-rhscl-7-rpms            0.0
    rh-nodejs6-npm                 noarch            3.10.9-2.el7            @rhel-server-rhscl-7-rpms            1.5 M

    Transaction Summary
    =====================================================================================================================
    Remove  1 Package (+2 Dependent packages)

    Installed size: 1.6 M


So the chain eventually leads us to `rh-nodejs6-npm`. From a cursory look, it doesn't seem like gyp is an optional component: npm has a number of dependencies on it in code.

**Comment by tmds** [comment]
Or maybe only remove the kernel-headers?

**Comment by omajid** [comment]
Yes, we can.

We can even leave gyp and nodejs packages installed and just remove the native things:

$ sudo rpm -e --nodeps glibc-headers glibc-devel gcc gcc-c++ kernel-headers

**Comment by tmds** [comment]
Super!

**Comment by tmds** [comment]
Next step will be to try this in a container and verify typical frontend things work as expected.

**Comment by omajid** [comment]
My knowledge of node/npm is non-existant. Someone more familiar should probably take a look.

**Comment by tmds** [comment]
I am not a frontend web developer either :) We need to do some investigation, pick some scenarios, and validate they still work. I'd be very surprised if this change would break things, so it's meant as a _smoke test_. Thanks for looking into the `yum`/`rpm` part already!

**Comment by tmds** [comment]
> We need to do some investigation, pick some scenarios, and validate they still work.

**Comment by tmds** [comment]
> sudo rpm -e --nodeps glibc-headers glibc-devel gcc gcc-c++ kernel-headers

Our 2.1 images don't have these packages. nodejs8 scl doesn't depend on them.

**Comment by tmds** [comment]
Fixed in https://github.com/redhat-developer/s2i-dotnetcore/pull/200
