### ISSUE TITLE
OpenShift Docker image containing source code

### ISSUE THREAD

**Issue by georgesak84** [redhat-developer/s2i-dotnetcore#202]
I'm working with dotnet core building and deploying micro-services using openshift, How can I prevent intruders to copy source code under app/src from docker images generated by Openshift Builder ! any method to not ship source code inside docker image ?

We already opened this issue at openshift origin following the below link replies:

https://github.com/openshift/origin/issues/20089

**Comment by tmds** [comment]
We can add an environment variable for this, e.g. `DOTNET_RM_SRC`.

In the meanwhile, you can add a script in your source repo at `.s2i/bin/assemble` with this content:
```sh
#!/bin/bash

# call base assemble script
$STI_SCRIPTS_PATH/assemble

# remove source code
rm -rf /opt/app-root/src /tmp/src
```

**Comment by atiato** [comment]
Hi tmds ,

Can you provide steps how we can add script inside openshift when we build the program and where in source repository we can add .s2i/bin/assemble!

Thanks,
Omar Atia

**Comment by tmds** [comment]
@atiato you don't need to change your OpenShift configuration, OpenShift will automatically see the file. Place a file `assemble` in a folder named `.s2i/bin`. For example: https://github.com/redhat-developer/s2i-dotnetcore-ex/tree/dotnetcore-1.0/.s2i/bin. I'm not sure if OpenShift needs it, but it is best to set the execute bit on this file. On Linux you can just `chmod +x <filename>`, see [this SO answer](https://stackoverflow.com/questions/40978921/how-to-add-chmod-permissions-to-file-in-git/40979016) how to do this on Windows.
To verify your assemble file is being used you can add an `echo` which will show up in your build log:
```sh
#!/bin/bash

# call base assemble script
$STI_SCRIPTS_PATH/assemble

# remove source code
echo "--> Removing source code ..."
rm -rf /opt/app-root/src /tmp/src
```

**Comment by georgesak84** [comment]
Thanks @tmds we tried it and it is working fine.

**Comment by tmds** [comment]
Great! I'll leave this open to add support for removing sources using an envvar.

**Comment by tmds** [comment]
This is implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/205.
