### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory, open '/opt/app-root/package.json'

### ISSUE THREAD

**Issue by farshid3003** [redhat-developer/s2i-dotnetcore#204]
Hi there is a problem with the package.json inside a folder
my project is inside a folder so package.json is there as well
I need to checkout project from the upper folder as it has some dependencis
so I cannot install npm packages
npm WARN enoent ENOENT: no such file or directory, open '/opt/app-root/package.json'
to me DOTNET_NPM_TOOLS parameter should shows the path of the package.json file
install the packages an webpack

**Comment by tmds** [comment]
`DOTNET_NPM_TOOLS` allows you to install some tools and does not use/depend on a `package.json` file in your repository.
You can `npm install` packages from a `package.json` file. This can be done from the `csproj` file. You can be explicit where your `package.json` file resides using the `WorkingDirectory` attribute.
For example, the default angular template has `package.json` under the `ClientApp` folder:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
...
    <SpaRoot>ClientApp\</SpaRoot>
...
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
...
</Project>
```
If this doesn't work, please provide a small reproducer that shows the issue.

**Comment by farshid3003** [comment]
Does not work,
<SpaRoot> beneath element <Project> is unrecognized

**Comment by farshid3003** [comment]
I found the solution thank you so much 

  <Target Name="BuildClientAssets" BeforeTargets="Build">
    <Exec Command="npm install" />
    <Exec Command="npm run build" />
  </Target>

**Comment by tmds** [comment]
No problem!
