### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by magick93** [redhat-developer/s2i-dotnetcore#219]
Hello

I'm trying to get started with 's2i-dotnetcore'. I've worked with various s2i builds before - mostly java.

I'm running the following script:

```
SERVER=SpikeCD750.Server
CLIENT=SpikeCD750

s2i build . dotnet/dotnet-21-centos7 ${SERVER,,} -e DOTNET_STARTUP_PROJECT=${SERVER}/${SERVER}.csproj -e DOTNET_APP_PATH=/opt/app-root/src/${SERVER}/bin/Release/netcoreapp2.1/ -e DOTNET_DEFAULT_CMD=${SERVER} -e DOTNET_APP_PATH=/opt/app-root/src/${SERVER}/bin/Release/netcoreapp2.1/
s2i build . dotnet/dotnet-21-centos7 ${CLIENT,,} -e DOTNET_STARTUP_PROJECT=${CLIENT}/${CLIENT}.csproj -e DOTNET_APP_PATH=/opt/app-root/src/${CLIENT}/bin/Release/netcoreapp2.1/ -e DOTNET_DEFAULT_CMD=${CLIENT} -e DOTNET_APP_PATH=/opt/app-root/src/${CLIENT}/bin/Release/netcoreapp2.1/
```

When I try to run either of these images, I get the following error:

```
server_1  | ---> Running application ...
server_1  | /usr/libexec/s2i/run: line 20: /opt/app-root/src/SpikeCD750.Server/bin/Release/netcoreapp2.1/SpikeCD750.Server.dll: Permission denied
ignite-readthrough_server_1 exited with code 1
client_1  | ---> Running application ...
client_1  | /usr/libexec/s2i/run: line 20: /opt/app-root/src/SpikeCD750/bin/Release/netcoreapp2.1/SpikeCD750.dll: Permission denied

```

I'm unsure how I should resolve this.
I thought `fix-permissions` would give correct permissions to the directory that has the executable in it.

## Update
I found that, in `s2i-dotnetcore/2.1/build/s2i/bin/run`, if I change:

`exec "./$DOTNET_DEFAULT_CMD"` to `dotnet "./$DOTNET_DEFAULT_CMD"` then it works. 
But the s2i tests fail.

**Comment by tmds** [comment]
> -e DOTNET_STARTUP_PROJECT=${SERVER}/${SERVER}.csproj -e DOTNET_APP_PATH=/opt/app-root/src/${SERVER}/bin/Release/netcoreapp2.1/ -e DOTNET_DEFAULT_CMD=${SERVER} -e DOTNET_APP_PATH=/opt/app-root/src/${SERVER}/bin/Release/netcoreapp2.1/

You shouldn't set `DOTNET_APP_PATH` or `DOTNET_DEFAULT_CMD`.
Only set `DOTNET_STARTUP_PROJECT` to point to the project file in your source repo.
