### ISSUE TITLE
How to delete source from runner?

### ISSUE THREAD

**Issue by magick93** [redhat-developer/s2i-dotnetcore#220]
Hello

I'm succesfully building my dotnet application using s2i-dotnetcore.

However, the runner image is, by default, placing the `/opt/app-root/src/${SERVER}/bin/Release/netcoreapp2.1/ -e DOTNET_DEFAULT_CMD=${SERVER} -e DOTNET_APP_PATH=/opt/app-root/src/${PROJECT}/bin/Release/netcoreapp2.1/`.

Also, in the working directory is the original source code.

How can I remove the source code, and is it possible to determine where the final build artifices are saved?

**Comment by tmds** [comment]
> However, the runner image is, by default, placing the /opt/app-root/src/${SERVER}/bin/Release/netcoreapp2.1/ -e DOTNET_DEFAULT_CMD=${SERVER} -e DOTNET_APP_PATH=/opt/app-root/src/${PROJECT}/bin/Release/netcoreapp2.1/

You should leave DOTNET_DEFAULT_CMD and DOTNET_APP_PATH at their default values. They are not meant to be changed by the user.
Setting DOTNET_STARTUP_PROJECT to a csproj file in your repo is enough.

> How can I remove the source code

You can remove all source-code after the build using DOTNET_RM_SRC=true.

> is it possible to determine where the final build artifices are saved?

Keeping this at the default is recommended.
