### ISSUE TITLE
DOTNET_STARTUP_PROJECT, contextDir, `.s2i/bin/*`

### ISSUE THREAD

**Issue by magick93** [redhat-developer/s2i-dotnetcore#230]
Hello

Currently I am building, successfully, using:

`s2i build . mydockerrepo/dotnet-21-centos7: ${env.PROJECT} -e DOTNET_STARTUP_PROJECT=${params.Project}/${params.Project}.csproj -e DOTNET_TEST_PROJECTS=${params.Project}.Tests/${params.Project}.Tests.csproj --pull-policy=always -e DOTNET_RM_SRC=true  --loglevel=5`

I would like to use a customized .s2i/bin/run and `.s2i/bin/assemble` - but only for this specific dotnetcore project.

When I add the `.s2i/bin/*` directory into the project, it is not picked up.
When I add it to the root it is. However, this is not ideal as Im trying to customize the s2i run for a specific project.

I've tried also specifying the `--context-dir` to be the same as the project, but when doing this the s2i build fails with:

```
I0928 11:58:59.418574    4343 sti.go:681] ---> Installing application source...
I0928 11:58:59.420271    4343 sti.go:685] mv: cannot stat '/tmp/src/*': No such file or directory
I0928 11:58:59.470454    4343 docker.go:1055] Waiting for container "58c06ad25c2144ea1ceebca3f5102916cd0de45074df3c71178022ec089c4352" to stop ...
I0928 11:58:59.678375    4343 docker.go:991] Removing container "58c06ad25c2144ea1ceebca3f5102916cd0de45074df3c71178022ec089c4352" ...
I0928 11:58:59.684552    4343 docker.go:1001] Removed container "58c06ad25c2144ea1ceebca3f5102916cd0de45074df3c71178022ec089c4352"
I0928 11:58:59.684849    4343 cleanup.go:33] Removing temporary directory /tmp/s2i975994351
I0928 11:58:59.684870    4343 fs.go:278] Removing directory '/tmp/s2i975994351'
I0928 11:58:59.685111    4343 build.go:171] Build failed
E0928 11:58:59.685127    4343 errors.go:276] An error occurred: non-zero (13) exit code from mydockerrepo/dotnet-21-centos7
```

**Comment by tmds** [comment]
> I would like to use a customized .s2i/bin/run and .s2i/bin/assemble - but only for this specific dotnetcore project.

the `.s2i` folder is an s2i feature and is not specific to the .NET Core builder so it is not aware of the DOTNET_STARTUP_PROJECT.

> I've tried also specifying the --context-dir to be the same as the project, but when doing this the s2i build fails with:
 mv: cannot stat '/tmp/src/*': No such file or directory

This means your context-dir is empty.
