### ISSUE TITLE
Specified framework not found error

### ISSUE THREAD

**Issue by gskumar1010** [redhat-developer/s2i-dotnetcore#238]
Hi,

Not sure if this is an issue, but checking.

We are using 
"dotnet-21-runtime-rhel7:latest" as the base image. 

When we have runtimeconfig.json as 
{
    "runtimeOptions": {
        "tfm": "netcoreapp2.1",
        "framework": {
            "name": "Microsoft.**AspNetCore**.App",
            "version": "2.1.1"
        },
        "configProperties": {
            "System.GC.Server": true
        }
    }
}
we run into below error.
The specified framework 'Microsoft.**AspNetCore**.App', version '2.1.1.' was not found.

  | - Check application dependencies and target a framework version installed at:
  | /opt/rh/rh-dotnet21/root/usr/lib64/dotnet/
"

Any ideas?

Thanks
Santosh

**Comment by tmds** [comment]
The ASP.NET Core framework is not part of the image. You need to include this as part of your application. You can do this by adding `/p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App` to the publish command. See this section of the documentation: https://access.redhat.com/documentation/en-us/net_core/2.1/html/getting_started_guide/gs_install_dotnet#publish_aspnet_apps.
