### ISSUE TITLE
test app.tar.gz has issues

### ISSUE THREAD

**Issue by gskumar1010** [redhat-developer/s2i-dotnetcore#239]
Hi,
Not able to open
https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.1/runtime/test/aspnet-hello-world/app.tar.gz 

Thanks
Santosh

**Comment by tmds** [comment]
you need to use the raw link to get a working app.tar.gz file: https://github.com/redhat-developer/s2i-dotnetcore/raw/master/2.1/runtime/test/aspnet-hello-world/app.tar.gz
