### ISSUE TITLE
Openshift Origin CentOS version

### ISSUE THREAD

**Issue by lobosan** [redhat-developer/s2i-dotnetcore#253]
Hi everyone, I'm new to Openshift and started using OKD to explore the platform to run .net core apps and after finding and using this template, postgres gets deployed but the app musicstore is not able to deploy because of this: "A new deployment will start automatically when an image is pushed to ncpro/musicstore:latest."

How can I get this example running on OKD?

**Comment by aslicerh** [comment]
Hi @lobosan,

If I had to guess, you either don't have the centos dotnet imagestream imported, or you didn't change the namespace of the template to match the namespace containing the centos dotnet images.

You can look under the 'Installing' section of the main readme for how to install an imagestream. Since you'd be installing the centos imagestream, you don't need to worry about any subscription or registry credentials.

By default, the template expects the imagestream to be installed under the 'openshift' namespace. If you decide to install the imagestream under a different namespace, then you need to make sure to change that paramater when you are deploying the template.

I know that might be a lot for someone new to Openshift, so does that make sense?

**Comment by lobosan** [comment]
Hi @aslicerh thanks for your quick response. I was able to do it after reading some docs and trying a couple of things. In the end this is what did it for me.

In my terminal executed the following lines for opeshift origin okd 3.11 and centos7 based imagestreams

```
$oc project <my-project>
$ wget https://raw.githubusercontent.com/redhat-developer/s2i-dotnetcore/master/install-imagestreams.sh
$ chmod +x install-imagestreams.sh
$ ./install-imagestreams.sh --os centos7
```

And then in Openshift, inside Builds > musicstore > Edit Builds Image Configuration > Build From
```
Image StreamTag
<my-project> / <dotnet> / <2.1>
```

However I have the following doubts:
- How can I add an imagestream globally?
- How can I add a template such as [dotnet-pgsql-persistent](https://github.com/openshift/origin/blob/master/examples/quickstarts/dotnet-pgsql-persistent.json) globally?
- What are the differences between [this template](https://github.com/openshift/origin/blob/master/examples/quickstarts/dotnet-pgsql-persistent.json) and [this one](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/templates/dotnet-pgsql-persistent.json)?

Thanks in advance for your help

**Comment by aslicerh** [comment]
@lobosan Glad to hear your got it working!

> How can I add an imagestream globally?
> How can I add a template such as dotnet-pgsql-persistent globally?

Anything added to the 'openshift' namespace should be available globally.

> What are the differences between this template and this one?

In theory, nothing. This is the upstream repo for that template, so all working changes go here. Then, at various points, this template is pulled down and merged into the openshift/origin repo, which causes it to get bundled up into the default openshift package.

So, depending on exactly how you're working with openshift (openshift online, minishift/CDK, the atomic-openshift RHEL package, etc.), these imagestreams and templates might already be imported and globally available, and all of those sync those imagestreams and templates from this repo.

**Comment by lobosan** [comment]
@aslicerh thanks again.

I just logged in as admin with the command
`oc login -u system:admin`
and then I switched to the openshift namespace
`oc project openshift`
and after that installed the template
`https://raw.githubusercontent.com/redhat-developer/s2i-dotnetcore/master/templates/dotnet-pgsql-persistent.json`
checked the imagestreams available for the namespace
`oc get imagestreams -n openshift`
so dotnet 2.1 was missing and therefore installed it
```
$ wget https://raw.githubusercontent.com/redhat-developer/s2i-dotnetcore/master/install-imagestreams.sh
$ chmod +x install-imagestreams.sh
$ ./install-imagestreams.sh --os centos7
```

Now I can create a new project and the template dotnet-pgsql-persistent is globally available and it runs out of the box since the correct imagestream is available in the correct namespace.

Thanks again for your help :)

**Comment by aslicerh** [comment]
@lobosan You're very welcome, and glad to hear everything is sorted out!

And thank you for replying with the commands you used to solve your problem, as it might help other people who come here with the same questions. That kind of thoroughness is something that would be really nice to see more often!
