### ISSUE TITLE
dotnet 2.2 centos images no integrated in dotnet_imagestreams_centos.json

### ISSUE THREAD

**Issue by Saphirim** [redhat-developer/s2i-dotnetcore#255]
Please add the dotnet 2.2 build and runtime images based on centos to the imagestreams definition file for centos.

**Comment by Saphirim** [comment]
Is this due to the missing dotnet-22-images on the centos7 registry?
What's necessary to proceed here?

![centosregistrydotnet](https://user-images.githubusercontent.com/7426446/50955772-43793400-14ba-11e9-851d-c0818dd49c6c.PNG)

**Comment by aslicerh** [comment]
There are two things needed for this, the first of which is getting the 2.2 containers into the centos build pipeline. I just put up the PR for that here: https://github.com/CentOS/container-index/pull/388

Once that is done, we'll need to update the imagestream file to add definitions for 2.2.

**Comment by Saphirim** [comment]
Thx for your reply.

Since I am not used to the process regarding the centos-maintainers, how long would you expcet the PR to last?

**Comment by aslicerh** [comment]
@Saphirim Hard to say, especially since this part is out of our hands, but I'd be surprised if the whole process (pipeline update and imagestream update) wasn't done within the next week or so.

**Comment by jozefizso** [comment]
How can we create and host our own build containers?

**Comment by aslicerh** [comment]
@Saphirim @jozefizso 
So, the updates to the Centos container pipeline have been merged, but there is an issue. The core team is not yet producing dotnet 2.2 RPMs. There will be no dotnet 2.2 Centos containers until that happens.

@jozefizso If the packages discussed above were available, then you could follow the instructions in the README here, and run the `build.sh` script to generate your own containers. After that you could import them to a container registry, or any other way you would normally host a container.

You could also fork the project and put together your own custom containers, if you wanted sometimes set up different than we provide.

**Comment by jozefizso** [comment]
I though the .NET Core 2.2 is available on CentOS: https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-current

**Comment by TheMidgardWatcher** [comment]
Hi all, 
I want to ask if there is some news regarding 2.2. CentOS images? Could we expect them in CentOS registry?

**Comment by TheMidgardWatcher** [comment]
Can somebody help with this?
https://github.com/CentOS/container-index/issues/392

**Comment by omajid** [comment]
I just spoke to @hughesjr on #centos-devel. Hopefully we will have 2.2 RPMs live by end of day today. Container images shouldn't take more than a few days, hopefully.

**Comment by TheMidgardWatcher** [comment]
Thanks @omajid for such a great news!

**Comment by TheMidgardWatcher** [comment]
dotnet 2.2 Images are now in registry and can be pulled. Thanks to all for great help!
