### ISSUE TITLE
dotnet-21-centos7 image throws "A compatible SDK version for global.json version" 

### ISSUE THREAD

**Issue by cagriersen** [redhat-developer/s2i-dotnetcore#263]
On a fresh installed OKD 3.10 cluster, I use registry.centos.org/dotnet/dotnet-21-centos7 as dotnet 2.1 imagestream, however all builds that uses this imagestream fail with the error below:

```
---> Restoring application dependencies...
A compatible SDK version for global.json version: [2.1.300] from [/opt/app-root/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
error: build error: non-zero (13) exit code from secopstech/dotnet-21-centos7@sha256:6d15318bc86c67061ecb7f1d9e7ff43a117bb27723ab3b35740d20b11f9e693b
```
The current image has dotnet version 2.1.503: 
```
bash-4.2$ dotnet --version
2.1.503
```
but DOTNET_SDK_BASE_VERSION environment which comes from Dockerfile points to version 2.1.300:

```
bash-4.2$ export |egrep DOTNET_SDK_BASE_VERSION
declare -x DOTNET_SDK_BASE_VERSION="2.1.300"
```
and it seems this situation leads to the error. 

If I change DOTNET_SDK_BASE_VERSION env to 2.1.500 than it works correctly.

**Comment by omajid** [comment]
@aslicerh  sounds like we need to explicitly install `rh-dotnet21-dotnet-sdk-2.1.3xx` now that centos includes multiple 2.1 sdk versions: http://mirror.centos.org/centos//7/dotnet/x86_64/Packages/

**Comment by tmds** [comment]
Fixed by https://github.com/redhat-developer/s2i-dotnetcore/pull/264/files
