### ISSUE TITLE
pull access denied for dotnet/dotnet-22-runtime-centos7

### ISSUE THREAD

**Issue by magick93** [redhat-developer/s2i-dotnetcore#285]
Hello

I'm trying to build, locally, version 2.2, but get the below error. 

I've tried searching in docker hub for `dotnet/dotnet-22-runtime-centos7` but there is no result.

```
sudo VERSIONS=2.2 ./build.sh
grep: /etc/redhat-release: No such file or directory
grep: /etc/redhat-release: No such file or directory
Running tests...
2.2/runtime/test/run: line 35: warning: command substitution: ignored null byte in input
[INFO] Using docker
[INFO] Testing dotnet/dotnet-22-runtime-centos7
[INFO] Running test_dotnet
[ERROR] Unable to find image 'dotnet/dotnet-22-runtime-centos7:latest' locally
docker: Error response from daemon: pull access denied for dotnet/dotnet-22-runtime-centos7, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
126 docker_run_withargs /home/anton/git/s2i-dotnetcore/2.2/runtime/test/testcommon
115 docker_run /home/anton/git/s2i-dotnetcore/2.2/runtime/test/testcommon
50 test_dotnet 2.2/runtime/test/run
202 main 2.2/runtime/test/run
[ERROR] '' does not contain 'Host'
63 assert_contains /home/anton/git/s2i-dotnetcore/2.2/runtime/test/testcommon
50 test_dotnet 2.2/runtime/test/run
202 main 2.2/runtime/test/run
Tests FAILED!
```

I've also tried doing `docker login` but logging in doesnt make any difference.

**Comment by jerboaa** [comment]
I believe the dotnet images are in the centos registry (not docker). Make sure you've got the centos registry configured as well, for example via `/etc/containers/registries.conf`. Centos registry is:

```
registry.centos.org
```

**Comment by magick93** [comment]
Thanks @jerboaa 

If I run `docker pull registry.centos.org/dotnet/dotnet-21-runtime-centos7` then it does pull the image, but then we I run `sudo VERSIONS=2.1 ./build.sh` I again get the above error.

I dont have either `/etc/containers/registries.conf` or `/etc/sysconfig/docker` files, so I'm not sure where I'm meant to add the new docker registry.

**Comment by aslicerh** [comment]
@magick93 

There are several places the config could be, depending on your docker version.

You say you have no `/etc/containers/registries.conf` or `/etc/sysconfig/docker`

Do you have a `/etc/docker/daemon.json`?

If you can pull using the full registry address, then the registry is accessible and the containers are available, it's just a question of where your particular docker/podman service reads the list of known registries from.

That said, the log piece you posted above means the script thinks that you already have those images available, since it didn't try to build them (which probably would have also failed, trying to pull the centos base image). Was that the full log?

**Comment by magick93** [comment]
Hi @aslicerh 

> Do you have a `/etc/docker/daemon.json`?

Yes I do.

> Was that the full log?

Yes

**Comment by magick93** [comment]
I've added `registry.centos.org` to `/etc/docker/daemon.json` and restarted the docker service.

Now, when I run `docker info` I get the following (note the presents of 'registry.centos.org'):

```
 docker info
Client:
 Debug Mode: false

Server:
 Containers: 84
  Running: 0
  Paused: 0
  Stopped: 84
 Images: 52
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.18.0-25-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.31GiB
 Name: dell
 ID: FVID:JC3V:7WQL:37HQ:MEFG:NPTA:JA4D:LLQB:KBMV:W5L3:KFQZ:AXFT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: magick
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.centos.org
  172.30.0.0/16
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

But, still, when I run `sudo VERSIONS=2.1 ./build.sh` I get the error in the initial post.

**Comment by aslicerh** [comment]
@magick93 

You added the centos registry as an insecure registry, which is understandable, but not quite correct. Insecure Registries are ones that do not communicate over HTTPS, and adding a registry as being allowed to be access insecurely still doesn't add it to the list of registries to check.

What you need to do is add the centos registry to the docker daemons options. I am less familiar on how to do this outside of the registries.conf file, [but here is a short doc from Docker discussing how to edit the daemon start options](https://success.docker.com/article/how-do-i-set-the-docker-daemon-options).

I believe the older version of docker used an `--add-registry` option to add addition registries, but with the current docs is may have changed to `--registry-mirror`

**Comment by magick93** [comment]
Thanks @aslicerh 

I've added `DOCKER_OPTS="--registry-mirror registry.centos.org"` to `/etc/default/docker`, restarted docker, and again run `sudo VERSIONS=2.1 ./build.sh` - but unfortunately I get the same error.

```
grep: /etc/redhat-release: No such file or directory
grep: /etc/redhat-release: No such file or directory
Running tests...
2.1/runtime/test/run: line 37: warning: command substitution: ignored null byte in input
[INFO] Using docker
[INFO] Testing dotnet/dotnet-21-runtime-centos7
[INFO] Running test_dotnet
[ERROR] Unable to find image 'dotnet/dotnet-21-runtime-centos7:latest' locally
docker: Error response from daemon: pull access denied for dotnet/dotnet-21-runtime-centos7, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
126 docker_run_withargs /home/anton/git/s2i-dotnetcore/2.1/runtime/test/testcommon
115 docker_run /home/anton/git/s2i-dotnetcore/2.1/runtime/test/testcommon
54 test_dotnet 2.1/runtime/test/run
209 main 2.1/runtime/test/run
[ERROR] '' does not contain 'Host'
63 assert_contains /home/anton/git/s2i-dotnetcore/2.1/runtime/test/testcommon
54 test_dotnet 2.1/runtime/test/run
209 main 2.1/runtime/test/run
Tests FAILED!
```

Can you tell me where in the project this error is coming from? Maybe I'm able to hardcode the registry, as I am able to successfully run `docker pull registry.centos.org/dotnet/dotnet-21-runtime-centos7`.

**Comment by aslicerh** [comment]
@magick93 
Run it again with DEBUG=true for more complete logging.

**Comment by magick93** [comment]
Hi @aslicerh 

I'm not sure how I should set this var, I tried as an env var and as a arg, eg `sudo VERSIONS=2.1 ./build.sh DEBUG=true` but in both cases I get the same output:

```
sudo VERSIONS=2.1 ./build.sh DEBUG=true
grep: /etc/redhat-release: No such file or directory
grep: /etc/redhat-release: No such file or directory
Running tests...
2.1/runtime/test/run: line 37: warning: command substitution: ignored null byte in input
[INFO] Using docker
[INFO] Testing dotnet/dotnet-21-runtime-centos7
[INFO] Running test_dotnet
[ERROR] Unable to find image 'dotnet/dotnet-21-runtime-centos7:latest' locally
docker: Error response from daemon: pull access denied for dotnet/dotnet-21-runtime-centos7, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
126 docker_run_withargs /home/anton/git/s2i-dotnetcore/2.1/runtime/test/testcommon
115 docker_run /home/anton/git/s2i-dotnetcore/2.1/runtime/test/testcommon
54 test_dotnet 2.1/runtime/test/run
209 main 2.1/runtime/test/run
[ERROR] '' does not contain 'Host'
63 assert_contains /home/anton/git/s2i-dotnetcore/2.1/runtime/test/testcommon
54 test_dotnet 2.1/runtime/test/run
209 main 2.1/runtime/test/run
Tests FAILED!
```

**Comment by magick93** [comment]
Ok found the solution.

On https://github.com/redhat-developer/s2i-dotnetcore/blob/master/build.sh#L109 if I change `image_prefix="dotnet"` to `image_prefix="registry.centos.org/dotnet"` then all tests work.

Am happy to do a PR if you like.

**Comment by magick93** [comment]
## Questions

I need to add a couple of assemblies to the runtime image, namely `leveldb`, ` libsqlite3-dev ` and `libunwind8-dev `. 

Is the best way to do this to add these to the `yum install` line in the dockerfile?

The intention is to use this image in Openshift, using s2i.

What is the recommend approach to deploying these modified images into an Openshift cluster?

**Comment by aslicerh** [comment]
@magick93 
Thanks for the debug log.

I don't think a PR is necessary. This script builds other things than centos, and we don't want to hardcode registries here if we can avoid it. It's just up to configuring docker/podman to know where to look, which might even change from user to user.

As for how to use them, normally we would recommend building on top of them. So you would build a new image from a dockerfile with a `FROM` line of our build image (such as `dotnet/dotnet-21-centos7`), have lines similar to in our dockerfiles with `USER 0`, `RUN yum install`, `USER 1001`, etc.

Then the image you built you can use with s2i just like our images, or with the openshift templates.
