### ISSUE TITLE
Change application of dotnet-pgsql-persistent.json template

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#294]
Currently we're using a fork of ASP.NET Core MusicStore (https://github.com/redhat-developer/s2i-aspnet-musicstore-ex). However, that application is meant for testing:

> This is a test application used for ASP.NET Core internal test processes. It is not intended to be a representative sample of how to use ASP.NET Core.

We should change to a more exemplary application, which is easy to update across .NET releases.

**Comment by tmds** [comment]
@omajid maybe we can use the app you put together for the launcher?

**Comment by omajid** [comment]
Sure. I can look into opening a PR with the output of the launcher as the new sample. Will that be used for all existing releases or just the new releases going forward?

**Comment by tmds** [comment]
> Will that be used for all existing releases or just the new releases going forward?

New releases.

The application is used by dotnet-pgsql-persistent.json template:

https://github.com/redhat-developer/s2i-dotnetcore/blob/76f1a1b32278681ef5185fe95d25b5094991566f/templates/dotnet-pgsql-persistent.json#L460

We can archive https://github.com/redhat-developer/s2i-aspnet-musicstore-ex when we have a fresh example app.

> I can look into opening a PR with the output of the launcher as the new sample. 

Can you put this in a repo named `redhat-developer/s2i-dotnetcore-persistent-ex.git`

You can can borrow some stuff (like README, LICENSE) from https://github.com/redhat-developer/s2i-dotnetcore-ex.git.

Branch names follow pattern `dotnetcore-[major].[minor]`.

The template passes a PostgreSQL `ConnectionString` envvar: https://github.com/redhat-developer/s2i-dotnetcore/blob/76f1a1b32278681ef5185fe95d25b5094991566f/templates/dotnet-pgsql-persistent.json#L222, which you can get from `IConfiguration`: https://github.com/redhat-developer/s2i-aspnet-musicstore-ex/blob/7a285971af16e71c1929f71fa90bc5d4eb0ac643/samples/MusicStore/ServiceCollectonExtension.cs#L20.

It would be nice if we can have this for 3.1.

**Comment by tmds** [comment]
I'm going to look at creating this based on https://github.com/tmds/dotnet-mssql-ex (which was based on ASP.NET documentation).

**Comment by tmds** [comment]
This is done.
