### ISSUE TITLE
manifest unknown on Docker Pull

### ISSUE THREAD

**Issue by kanadaj** [redhat-developer/s2i-dotnetcore#303]
I'm getting a `manifest unknown` error when trying to pull the 3.0 image from the CentOS Registry:

```
$ docker pull registry.centos.org/dotnet/dotnet-30-runtime-centos7:latest
Error response from daemon: manifest for registry.centos.org/dotnet/dotnet-30-runtime-centos7:latest not found: manifest unknown: manifest unknown
```

**Comment by tmds** [comment]
I think these images haven't been build yet for CentOS.
You can follow this issue: https://github.com/CentOS/container-index/issues/404
