### ISSUE TITLE
Dotnet core 3.1 images

### ISSUE THREAD

**Issue by TheMidgardWatcher** [redhat-developer/s2i-dotnetcore#307]
Hi,

I have a question, when we could expect dotnetcore 3.1 images in catalog.redhat.com

PS. Sorry if this question is not related to you, i would greatly appreciate if you could guide me where i can ask this question.

**Comment by RheaAyase** [comment]
Hi, Red Hat release management is currently experiencing some outage so although these are ready, they're not out yet. Can't give any estimates but I can post an update here when it's out.

(And for the record I'm talking about RHEL7-base, not UBI8, that's a whole another story.)

**Comment by TheMidgardWatcher** [comment]
Thank you @RheaAyase for quick response, it would be wonderful if you will post an update.
And yes, we interested in rh7 images, not UBI8.

**Comment by RheaAyase** [comment]
If you don't mind a minute and have a Red Hat account, could you please open a support ticket (you can link to this issue if you want) - it helps us get more official customer feedback :)

**Comment by RheaAyase** [comment]
.NET Core 3.1 RHEL7-base images are now live.

**Comment by TheMidgardWatcher** [comment]
@RheaAyase is this images are the same as it was previously for dotnet 2.x on Centos7?

**Comment by aslicerh** [comment]
@TheMidgardWatcher Unfortunately, we can't build centos containers until the RPMs are available, and they are not yet. We have everything in place to enable that once the RPMs are available though.

**Comment by TheMidgardWatcher** [comment]
> @TheMidgardWatcher Unfortunately, we can't build centos containers until the RPMs are available, and they are not yet. We have everything in place to enable that once the RPMs are available though.

As I remember, we faced such issue previously with dotnet:2.2, but someone helped to push another team to release this rpms. Maybe we could try to do it one more time? Could you advise me with repo/project where I can open issue to get rpms faster?

**Comment by TheMidgardWatcher** [comment]
@aslicerh , @RheaAyase  Could you please take a look into issue I've mentioned above?

**Comment by TheMidgardWatcher** [comment]
@aslicerh I've mentioned you in https://github.com/CentOS/container-index/issues/404, could you please take a look?

**Comment by tmds** [comment]
Closing since rhel7 images are available.
For CentOS images, see https://github.com/CentOS/container-index/issues/404.

**Comment by aslicerh** [comment]
3.1 images are now also available on rhel8/ubi8.

https://catalog.redhat.com/software/containers/search?q=dotnet%203.1
