### ISSUE TITLE
Certificates are not linked on binary build

### ISSUE THREAD

**Issue by kandersen82** [redhat-developer/s2i-dotnetcore#308]
When building an image from binary the assemble script never calls the script that trust certificates from DOTNET_SSL_DIRS. This results in an image without the required certificate links in /opt/app-root/ssl_dir.

This seems to be an issue for both dotnet 3.0 and 3.1. I have not tested on previous versions.

**Comment by tmds** [comment]
@kandersen82 this should happen when the `container-entrypoint` script runs.

https://github.com/redhat-developer/s2i-dotnetcore/blob/4b93a263047f6db9b4cc256dc852163220cbfbbc/3.1/runtime/root/usr/bin/container-entrypoint#L15-L23

Does the runtime container have `DOTNET_SSL_DIRS` set?

Can you provide some steps to reproduce?

**Comment by kandersen82** [comment]
Hi @tmds. We have since changed the way we build images, so i am a bit unsure if this was caused by a missing environment variable like you mention. I will close the issue, no need to investigate further.
