### ISSUE TITLE
Test s2i-dotnetcore-persistent-ex against postgresql

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore#313]
@tmds asked in #310 :

> It would be nice if we checked s2i-dotnetcore-persistent-ex works against postgresql database, matching instructions from the documentation.

**Comment by tmds** [comment]
This was created in context of a script to test the image streams.

I'm not using that script, I prefer to manually check the image streams and our sample applications, and see what happens in OpenShift.

Closing this issue.
