### ISSUE TITLE
Overriding LD_PRELOAD

### ISSUE THREAD

**Issue by lrgar** [redhat-developer/s2i-dotnetcore#319]
Hello,

We, on Dynatrace, use the environment variable `LD_PRELOAD` to inject our monitoring library into applications. We had a case with a customer where this didn't work because the environment variable gets overridden on the entrypoint.

Could it be possible to update the script so that it doesn't get overridden but appended perhaps? For example,
https://github.com/redhat-developer/s2i-dotnetcore/blob/971e0f8e357230665e2ba28b197648f6edfcecf9/2.1/runtime/contrib/etc/generate_container_user#L21
```diff
-LD_PRELOAD=libnss_wrapper.so
+LD_PRELOAD="libnss_wrapper.so ${LD_PRELOAD}"
```

I'm open to create a PR if preferred.

Thanks in advance and best regards,
Luis

**Comment by omajid** [comment]
Sounds good to me. I think we should make this change in all supported versions: 2.1 and 3.1

**Comment by lrgar** [comment]
Thanks, in that case I'll create a PR with the changes for 2.1, 3.0, and 3.1.

**Comment by omajid** [comment]
> Thanks, in that case I'll create a PR with the changes for 2.1, 3.0, and 3.1.

3.0 is EOL; we probably wont be doing any further updates to it.
