### ISSUE TITLE
How to add compilation symbols?

### ISSUE THREAD

**Issue by Metrowerks** [redhat-developer/s2i-dotnetcore#320]
Hi, how can I add compilation symbols to my S2I build? I have tried using the DOTNET_CONFIGURATION variable but it seems to only allow Release or Debug. For example, I want to use a symbol OPENSHIFT in my code to enable certain blocks of code when I build my solution. How would I define this symbol and use it in the S2I build?

I'm using the .Net Core 2.1 Docker image in OpenShift.

**Comment by omajid** [comment]
Hi. Sorry about the delay in getting back to you. 

Can you please provide some additional details to help us observe this problem on our end? And to verify that any fixes we develop solve this problem for you?

In particular, do you have a [Minimal, Reproducible Example ](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue? We would like to know the code that you are building (could be a Hello-World type example), images you are using and any s2i commands you are running as well what you expected vs what you see.

**Comment by Metrowerks** [comment]
Hi, it's just about using compilation symbol to control building code block. For example, I want to add AuthorizeAttribute to MyConntroller only if it's in Openshift, by using the OPENSHIFT symbol. Right now it's not possible to add custom symbol to the build configuration, except for DEBUG and RELEASE. 
```c#
#if OPENSHIFT
    [Authorize]
#endif
public class MyController : ControllerBase
{
 ....
}
```

anyhow, I have found a way to configure it so I'm going to close this one

**Comment by omajid** [comment]
> anyhow, I have found a way to configure it so I'm going to close this one

That's great! If you can, please share it here so others who might want to do this can find out how you did it too.

**Comment by Metrowerks** [comment]
Certainly!

You can define a conditional variable in the csproj that in fact reads from an environment variable. Then in the build configuration in OpenShift, you can simply define that environment variable to control the custom compilation symbol at run time.

Something like this:
```xml
  <PropertyGroup>
...
    <IsOpenShift Condition="$([System.Environment]::GetEnvironmentVariable('OCP')) == 'true'">true</IsOpenShift>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOpenShift)'=='true'">
    <DefineConstants>OPENSHIFT</DefineConstants>
  </PropertyGroup>
```
Then in the build configuration in OpenShift, you just need to define the `OCP `environment variable and set it to `true`.
