### ISSUE TITLE
Single project file, which is not at project root, is not automatically picked up

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore#325]
I created a simple project with only one `.csproj` file at `src/Secret/Secret.csproj`. Building that in OpenShift fails when I dont set `DOTNET_STARTUP_PROJECT`:

```
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source...
error: DOTNET_STARTUP_PROJECT has no project file
You can specify the startup project by adding an '.s2i/environment' file to the source repository.
The source repository contains the following projects:
- src/Secret/Secret.csproj
Update the '.s2i/environment' file to specify the project you want to publish, for example DOTNET_STARTUP_PROJECT=src/Secret/Secret.csproj.
subprocess exited with status 1
```

Since the error shows the project file, and there's only a single project file should we just use that and not error out?

The code that tries to find a default `DOTNET_STARTUP_PROJECT` only looks in the main directory:

https://github.com/redhat-developer/s2i-dotnetcore/blob/c77d93d1f35ef4d7fb7757a8ea6503622662e7c7/3.1/build/s2i/bin/assemble#L38

**Comment by tmds** [comment]
I prefer to not potentially execute the wrong thing. Or stop working when more projects get added.

similar UX: `dotnet` cli doesn't search subdirs.
```
$ dotnet run
Couldn't find a project to run. Ensure a project exists in /tmp/root, or pass the path to the project using --project.
```

**Comment by omajid** [comment]
That's a good point. I am going to close this issue then.
