### ISSUE TITLE
execute multiple commands dotnet in script bash in Redhat

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [redhat-developer/s2i-dotnetcore#328]
Hello Guys,

I need help to excuste some commands in the same script bash, i used redhat

````````````````````````
#!/bin/bash

###############################################################################
#Script Name    : vsmpscript.sh
#Description    : execute multiple commands
#Author         : HASSEN MEDDEB
#Email          : hassen.meddeb@
################################################################################

cd /home/user/VSMP_Data_Integration \
&& export https_proxy=http://150.150.150.1:8080 \
&& echo $http_proxy
&& export http_proxy=http://150.150.150.1:8080 \
&& echo $http_proxy
&& scl enable rh-dotnet31 bash \
&& dotnet restore \
&& dotnet build \
&& dotnet publish -f netcoreapp3.1 -c Release \
&& cd /home/user/VSMP_Data_Integration/VSMP_Contracts_Import/bin/Release/netcoreapp3.1/publish \
&& .VSMP_Contracts_Import \

```````````````````

Cordially

**Comment by omajid** [comment]
I assume that the problem is that the `scl` command, followed by `dotnet` isn't working as you expect it to?

`scl` creates a new shell, and `dotnet` will only work within that shell. I suggest that you change your script to remove the `scl` command:

```sh
#!/bin/bash

cd /home/user/VSMP_Data_Integration \
&& export https_proxy=http://150.150.150.1:8080 \
&& echo $http_proxy
&& export http_proxy=http://150.150.150.1:8080 \
&& echo $http_proxy
&& dotnet restore \
&& dotnet build \
&& dotnet publish -f netcoreapp3.1 -c Release \
&& cd /home/user/VSMP_Data_Integration/VSMP_Contracts_Import/bin/Release/netcoreapp3.1/publish \
&& .VSMP_Contracts_Import \
```

And run your script using scl:

    scl enable rhdotnet31 ./vsmpscript.sh

Btw, there's a couple of other issues with your script (syntax, style, etc). I would do it like this https://gist.github.com/omajid/bb33f007ee9e36d976b45479ea124ef8

**Comment by aslicerh** [comment]
Also, your first echo should be $http**s**_proxy.

Also, is that last line supposed to be running your executable? If so, it should be:
dotnet _dll-name_

Lastly, is this being run in a container, or is this just a general issue you're having running a dotnet application?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Thanks guys, it work like a charm :D
