### ISSUE TITLE
dotnet-example template references missing ImageStream tag by default

### ISSUE THREAD

**Issue by adambkaplan** [redhat-developer/s2i-dotnetcore#332]
The dotnet-example template that ships in OpenShift references version 3.0 by default. This has been deprecated and the related imagestream tag is not installed on new OpenShift clusters.

The template should be updated to reference an appropriate version of .NET by default.

See https://bugzilla.redhat.com/show_bug.cgi?id=1869522

**Comment by tmds** [comment]
We are no longer maintaining this template. It will no longer be included in OpenShift: https://github.com/openshift/library/pull/250.
