### ISSUE TITLE
Question: .NET 5 support

### ISSUE THREAD

**Issue by matthewpwilson** [redhat-developer/s2i-dotnetcore#340]
When is a UBI base image for .NET 5 likely to be available please?

**Comment by RheaAyase** [comment]
When .NET5 is released :p

**Comment by RheaAyase** [comment]
(Without much of a lag, if any at all.)

**Comment by Alexr03** [comment]
Was also about to ask this. Thanks ^^

**Comment by matthewpwilson** [comment]
Great, thanks for the quick response.

**Comment by RheaAyase** [comment]
UBI8 is now available with .NET 5 **preview 8** 
https://catalog.redhat.com/software/containers/search?q=ubi8%2Fdotnet-50&p=1
