### ISSUE TITLE
.NET icon

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#342]
In our image-streams file we refer to `icon-dotnet`.

This results in OpenShift showing this image:

![logo_NETcore](https://user-images.githubusercontent.com/1025424/100586401-62bc1d00-32ef-11eb-8c60-bfd3cde85657.png)

With .NET 5, _Core_ got dropped from _.NET Core_ and we should do the same in this image.

We may use a logo from: https://github.com/dotnet/brand/tree/master/logo.

![dotnet-logo](https://user-images.githubusercontent.com/1025424/100586691-d3fbd000-32ef-11eb-864a-24a10893fd99.png)

@yselkowitz @adambkaplan how/where can we make this change?

cc @aslicerh @omajid

**Comment by yselkowitz** [comment]
https://github.com/openshift/console/blob/master/frontend/public/imgs/logos/dotnet.svg

**Comment by tmds** [comment]
Created https://github.com/openshift/console/pull/7373 to update the logo.

**Comment by tmds** [comment]
This is fixed.
