### ISSUE TITLE
.NET 5 images cannot be built for CentOS

### ISSUE THREAD

**Issue by barthermans** [redhat-developer/s2i-dotnetcore#343]
When I try to build the centos runtime-5.0 image, it fails with this message:

```package rh-dotnet31-aspnetcore-runtime-5.0 is not installed
The command '/bin/sh -c yum install -y centos-release-dotnet &&     INSTALL_PKGS="rh-dotnet31-aspnetcore-runtime-5.0 nss_wrapper tar unzip" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all -y &&     rm -rf /var/cache/yum/*' returned a non-zero code: 1
```

There seems to be a reference to dotnet31, is that correct?
https://github.com/redhat-developer/s2i-dotnetcore/blob/4c2802608b12a41546e4436c386a94887c60acf9/5.0/runtime/Dockerfile#L51-L55

**Comment by tmds** [comment]
> There seems to be a reference to dotnet31, is that correct?

That's a bug. Do you want to send a PR to fix it? Otherwise, I'll take a look.

We are still working with Microsoft to be able to build .the final 5.0 packages for RHEL, see https://github.com/dotnet/core/issues/5596.

RHEL 7 `Dockerfile` won't work because of that.
RHEL 8 `Dockerfile.rhel8` should work and use the preview8 packages.

cc @aslicerh @omajid

**Comment by michaelbanzatto** [comment]
@tmds I've tried change the pkg name, but didn't work.
"rh-dotnet not installed".

Any news?

**Comment by omajid** [comment]
CentOS 7 doesn't seem to have built any `rh-dotnet50*` packages yet: http://mirror.centos.org/centos/7/dotnet/x86_64/Packages/. I see 1.x, 2.x, 3.x but no 5.x. If you are using CentOS 7, can you reach out the CentOS maintainers and ask them for that?

**Comment by aslicerh** [comment]
@michaelbanzatto, @tmds, @omajid, @barthermans 

5.0 packages should be available now. Can someone report back that builds are working for them as expected?

**Comment by barthermans** [comment]
@aslicerh did a quick test, but getting this error now:
```
Step 19/21 : RUN chown -R 1001:0 /opt/app-root && fix-permissions /opt/app-root
 ---> Running in aeaedda8b511
/bin/sh: /usr/bin/fix-permissions: /bin/sh^M: bad interpreter: No such file or directory
The command '/bin/sh -c chown -R 1001:0 /opt/app-root && fix-permissions /opt/app-root' returned a non-zero code: 126
```

**Comment by aslicerh** [comment]
@barthermans 

I can't replicate that on my systems. What OS are you building the images on?

**Comment by barthermans** [comment]
@aslicerh Windows 10

**Comment by barthermans** [comment]
Haven't had time yet to test the images, but they're building, so I'm closing this issue.

**Comment by tmds** [comment]
The tests passed on the CI server for `dotnet-50-centos7`.
