### ISSUE TITLE
EOL versions

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#344]
We've been removing EOL versions from our imagestreams.

There is a KB article for .NET Core about previous versions being missing after installing the latest imagestreams: https://access.redhat.com/solutions/4817081.

@yselkowitz is removing the EOL versions the recommended practice? An alternative may be to mark them as `hidden`?

cc @omajid @aslicerh

**Comment by yselkowitz** [comment]
Standard practice in OpenShift is to outright remove references to EOL versions.

**Comment by yselkowitz** [comment]
Left a comment on the KB accordingly.

**Comment by tmds** [comment]
Thanks @yselkowitz
