### ISSUE TITLE
Bug in install script in windows

### ISSUE THREAD

**Issue by faysou** [redhat-developer/s2i-dotnetcore#346]
This code needs to be removed in this file, else the help is always displayed
https://github.com/redhat-developer/s2i-dotnetcore/blob/master/install-imagestreams.ps1

If ( $args.Count -eq 0 )
{
	Say -wildcard ( $OS )
    Get-Help $PSCommandPath
    exit
}

After removing this I managed to get it installed in CRC while logged as kubeadmin using 
.\install-imagestreams.ps1 -OS rhel -Namespace openshift -User $user1 -Password $password1

Using a login obtained from https://access.redhat.com/RegistryAuthentication

**Comment by omajid** [comment]
Thanks for reporting this!

@tmds It looks like `$args` refers to all unbound arguments (only). If any parameters are bound via `params`, they still result in `$args.Count -eq 0`.

https://stackoverflow.com/a/61012813/3561275 suggests using `$PSBoundParameters.Values.Count -eq 0 -and $args.count -eq 0` to detect the case where there are no bound parameters and no arguments.

**Comment by tmds** [comment]
@faysou thanks for reporting this issue, and congrats for probably being the first person to use the Windows script :smile:.

This should fix the problem: https://github.com/redhat-developer/s2i-dotnetcore/pull/347.
