### ISSUE TITLE
How to specify credentials when using DOTNET_RESTORE_SOURCES

### ISSUE THREAD

**Issue by askids** [redhat-developer/s2i-dotnetcore#349]
hi,

In my build config, if I am using DOTNET_RESTORE_SOURCES to provide list of Nuget feeds and if they need to be connected using specific credentials, how do i provide user id/password for it?

Thanks!

**Comment by omajid** [comment]
I can't think of an obvious solution here other than using a custom `nuget.config` file.

Any ideas @aslicerh @tmds ?

**Comment by tmds** [comment]
I wonder if you can add credentials in the http url: `http://user:password@host/...`.

**Comment by noamichael** [comment]
I've also be struggling with this. 

I'm trying to authenticate to a NuGet feed during an OpenShift s2i build. My first idea was to have the `NuGet.Config` exist on the same level as the `*.csproj` file and parameterize the username and password:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="myregistry" value="https://myregistry.example.com/nuget" />
  </packageSources>
  <packageSourceCredentials>
    <artifactory>
      <add key="Username" value="%NUGET_USER%" />
      <add key="ClearTextPassword" value="%NUGET_PASSWORD%" />
    </artifactory>
  </packageSourceCredentials>
</configuration>
```

Then, I could use a secret to setup `NUGET_USER` and `NUGET_PASSWORD` as environment variables during the build. The issue with this is that OpenShift 4.x lists all of the environment variables  (even the ones setup to pull from secrets!) in one of the s2i init containers during the build, so you can see the credentials in plain text.

The next idea I had was to mount the entire `NuGet.Config` using the `secrets` option on `BuildConfig` ([Build Secrets](https://docs.openshift.com/container-platform/4.7/cicd/builds/creating-build-inputs.html#builds-adding-input-secrets-configmaps_creating-build-inputs)). The issue with this option is that is ends up creating a symlink in the `WORKDIR` of the image, which is `/opt/app-root`. This symlink is owned by `root`, and when the `fix-permissions` util runs at the end of the `assemble` script, it fails to change the permissions on the `NuGet.Config` symlink, so the whole build fails:


```
---> Installing application source...
Using SDK: 3.1.113
---> Restoring application dependencies...
Restore completed in 6.3 sec for /opt/app-root/src/app/app.csproj.
---> Publishing application...
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
app -> /opt/app-root/src/app/bin/Release/netcoreapp3.1/app.dll
app -> /opt/app-root/src/app/bin/Release/netcoreapp3.1/app.Views.dll
app -> /opt/app-root/app/
chgrp: changing group of '/opt/app-root/src/..2021_04_09_17_27_09.214086971/NuGet.Config': Operation not permitted
chgrp: changing group of '/opt/app-root/src/..2021_04_09_17_27_09.214086971': Operation not permitted
chgrp: changing group of '/opt/app-root/src/..data': Operation not permitted
chgrp: changing group of '/opt/app-root/src/NuGet.Config': Operation not permitted
chmod: changing permissions of '/opt/app-root/src/..2021_04_09_17_27_09.214086971': Operation not permitted
chmod: changing permissions of '/opt/app-root/src/..2021_04_09_17_27_09.214086971/NuGet.Config': Operation not permitted
chmod: changing permissions of '/opt/app-root/src/..2021_04_09_17_27_09.214086971': Operation not permitted
error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/openshift/dotnet-31-rhel7@sha256:b820b28ceec45d7c217a6f8b91d8aaeaef3f971734e7deb3759eb550f74be190
F0409 17:28:14.712397    2043 helpers.go:119] error: the build dotnetcore-example-2 status is "Failed
```

Any ideas of what we can do?

**Comment by tmds** [comment]
There is an envvar you can point to the NuGet.Config file: `DOTNET_RESTORE_CONFIGFILE`:

> Specifies a NuGet.Config file to be used for restore operations. This variable cannot be combined with DOTNET_RESTORE_SOURCES.

**Comment by noamichael** [comment]
> There is an envvar you can point to the NuGet.Config file: `DOTNET_RESTORE_CONFIGFILE`:

@tmds That's okay, but how can I get the `NuGet.Config` file into the build pod? It can't exist directly in source code since it contains account credentials, so it must be stored in an OpenShift secret. If you see my comment above, using build input secrets fails because you can only mount the secrets relative to the current image `WORKDIR`, which eventually gets run through `fix-permissions` at the end of the `assemble` script. Any ideas on how to solve this?

**Comment by tmds** [comment]
> If you see my comment above, using build input secrets fails because you can only mount the secrets relative to the current image WORKDIR,

Did you try setting `destinationDir` to a folder outside `WORKDIR`? That didn't work?

**Comment by noamichael** [comment]
I did try that, and it seems it has to be mounted somewhere in the `WORKDIR`:

```
Reason: BuildConfig.build.openshift.io "dotnetcore-example" is invalid: spec.source.secrets[0].destinationDir:

Invalid value: "../": destination dir cannot start with '..'
```

**Comment by tmds** [comment]
What happens with a rooted path, like `/mysecrets'?

**Comment by noamichael** [comment]
Thanks @tmds  - that seems to have worked! The docs around `destinationDir` don't talk about using absolute paths. They make it seem it has to be relative, but absolute paths worked. I wish I would have tested that earlier.

So the full answer to this issue is:

- Create a NuGet.Config which contains your private registry and credentials
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="myregistry" value="https://myregistry.example.com/nuget" />
  </packageSources>
  <packageSourceCredentials>
    <myregistry>
      <add key="Username" value="NUGET_USER" />
      <add key="ClearTextPassword" value="NUGET_PASSWORD" />
    </myregistry>
  </packageSourceCredentials>
</configuration>
```
- Upload the `NugGet.Config` to OpenShift as a `Secret`. Make sure the data key is `NuGet.Config`.
- Update your `BuildConfig` to mount the secret outside of the images `WORKDIR` and point `DOTNET_RESTORE_CONFIGFILE` to the correct path
```json
{
	"kind": "BuildConfig",
	"apiVersion": "v1",
	"metadata": {
		"name": "${COMPONENT_NAME}"
	},
	"spec": {
		"source": {
			"type": "Git",
			"git": {
				"uri": "${SOURCE_REPOSITORY_URL}",
				"ref": "${SOURCE_REPOSITORY_REF}"
			},
			"contextDir": "${CONTEXT_DIR}",
			"sourceSecret": {
				"name": "gitsecret"
			},
			"secrets": [{
				"secret": {
					"name": "nuget-config"
				},
				"destinationDir": "/secrets"
			}]
		},
		"strategy": {
			"type": "Source",
			"sourceStrategy": {
				"from": {
					"kind": "ImageStreamTag",
					"namespace": "openshift",
					"name": "dotnet-31-rhel7:latest"
				},
				"env": [{
					"name": "DOTNET_RESTORE_CONFIGFILE",
					"value": "/secrets/NuGet.Config"
				}]

			}
		}
	}
}
```

**Comment by tmds** [comment]
@noamichael great you got it working! That is a proper solution using secrets and `DOTNET_RESTORE_CONFIGFILE`.

If someone would like to use `DOTNET_RESTORE_SOURCES`, they can make a feature request for NuGet to allow providing a username/password in the url (if that is not yet supported).
