### ISSUE TITLE
Feature: print cgroup limits interpreted by .NET

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#352]
It would be nice if we could print out the cgroup limits when a build is performed, and when the application is executed.

This could be enabled with an envvar.

As part of the sdk build, we can build a .NET application that is included in the image and prints the information.

The app would do something like:

```cs
Console.WriteLine($"Processor Count: {Environment.ProcessorCount}");
Console.WriteLine($"Memory Limit:    {GC.GetGCMemoryInfo().TotalAvailableMemoryBytes}");
```

When the envvar is set, we run this pre-compiled application, before we do the other steps.

This will add a few kb to our SDK image.

@omajid @aslicerh wdyt?

**Comment by aslicerh** [comment]
This sounds good to me.

**Comment by tmds** [comment]
Implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/353
