### ISSUE TITLE
package rh-dotnet31-aspnetcore-runtime-5.0 is not installed

### ISSUE THREAD

**Issue by Exist2Resist** [redhat-developer/s2i-dotnetcore#355]
Trying to build the package I get the following error.

`

package rh-dotnet31-aspnetcore-runtime-5.0 is not installed
--
  | Removing intermediate container 84fc70eaee1c
  | error: build error: The command '/bin/sh -c yum install -y centos-release-dotnet &&     INSTALL_PKGS="rh-dotnet31-aspnetcore-runtime-5.0 nss_wrapper tar unzip" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all -y &&     rm -rf /var/cache/yum/*' returned a non-zero code: 1

`

**Comment by aslicerh** [comment]
Hello @Exist2Resist 

Unfortunately, .NET 5.0 packages don't seem to be available in the Centos repos (which is why you're seeing this error). Let me get in contact with upstream packaging and see what needs to happen to change that.

**Comment by Exist2Resist** [comment]
Appreciate it, thank you.

**Comment by tmds** [comment]
Package name is fixed by https://github.com/redhat-developer/s2i-dotnetcore/pull/356.

Missing CentOS support is dup with https://github.com/redhat-developer/s2i-dotnetcore/issues/343.
