### ISSUE TITLE
Create a centos based mirror image

### ISSUE THREAD

**Issue by jerboaa** [redhat-developer/s2i-dotnetcore#36]
It would be great if the community had a centos-based mirror image available which could get loaded into OpenShift Origin releases by default. Right now the best thing close to a community image is https://github.com/openshift-s2i/s2i-aspnet but that diverges more and more from s2i-dotnetcore.

**Comment by omajid** [comment]
I was informed by CentOS folks that the 1.x RPMs are now available for CentOS too.

**Comment by omajid** [comment]
cc @aslicerh

**Comment by omajid** [comment]
See `centos-release-dotnet` RPMs that are now available in CentOS extras repo.

**Comment by omajid** [comment]
I helped Che folks write up https://github.com/eclipse/che-dockerfiles/pull/135. We can use that as our starting point.

**Comment by tmds** [comment]
Implemented for 2.0 in https://github.com/redhat-developer/s2i-dotnetcore/pull/133.

**Comment by omajid** [comment]
Should we keep this issue open until the images are published somewhere?

**Comment by tmds** [comment]
I typically close them when the code is merged.
