### ISSUE TITLE
.NET Core 3.1 application not finding environment variable

### ISSUE THREAD

**Issue by boukisge** [redhat-developer/s2i-dotnetcore#363]
I cannot get my .NET Core 3.1 console application to recognize user defined  environment variables created via configmap . This approach worked fine for a web component for  some reason it does not work with a console application

**Comment by omajid** [comment]
Hi @boukisge ! Thanks for reporting this issue. Can you share the source code of a simple (Hello World-style) application that lets you see this issue? If it works for a web component (an ASP.NET Core application?) and doesn't work for a console app, then I am definitely interested in how the console app is reading the environmental configuration.

**Comment by boukisge** [comment]
Issue resolved. We are able to read environment variables from a dotnet
console app.

**Comment by omajid** [comment]
Glad you were able to get it working! Thanks for keeping us updated.
