### ISSUE TITLE
Error while connecting to MSSQL Server (error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small)

### ISSUE THREAD

**Issue by amrosama2020** [redhat-developer/s2i-dotnetcore#366]
I get the following exception while trying to connect to a MSSQL server:
```
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
       ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
       ---> Interop+Crypto+OpenSslCryptographicException: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
         --- End of inner exception stack trace ---
         at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount) in /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 282
         at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 114
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 393
```

After a bit of research the cause of this issue is here: [https://github.com/dotnet/runtime/issues/30667#issuecomment-524355267](https://github.com/dotnet/runtime/issues/30667#issuecomment-524355267)

Which requires changing this:
CipherString = DEFAULT:@SECLEVEL=2
To:
CipherString = DEFAULT:@SECLEVEL=1

In /etc/ssl/openssl.cnf

This exception is happening on **dotnet:5.0-ubi8** only, 3.1 is working fine.

I'm aware that this may not classify as an issue, but I was wondering if we can have an environment variable to change this openssl config or if someone has another fix for this error.

**Comment by omajid** [comment]
cc @aslicerh

**Comment by tmds** [comment]
> CipherString = DEFAULT:@SECLEVEL=1

This lowers the security level and allows more algorithms to be used.

> I'm aware that this may not classify as an issue, but I was wondering if we can have an environment variable to change this openssl config or if someone has another fix for this error.

Using `SslClientAuthenticationOptions.CipherSuitesPolicy` it's possible to control the ciphers used. Unfortunately `SqlClient` doesn't allow you to set this, so it uses the system default.

Neither the user that builds the image, nor the user that executes the application have rights to edit `/etc/ssl/openssl.cnf`.

You need to create an image `FROM dotnet:5.0-ubi8`. In the `Dockerfile` you change to `USER 0`, then make the edits to the `openssl.cnf`, and then change back to `USER 1001`.
