### ISSUE TITLE
Related to https://github.com/gorkem/java-language-server/issues/40

### ISSUE THREAD

**Issue by max2max4u** [redhat-developer/s2i-dotnetcore#367]
Related to https://github.com/gorkem/java-language-server/issues/40

_Originally posted by @gorkem in https://github.com/redhat-developer/vscode-java/issues/10#issuecomment-246640959_

**Comment by omajid** [comment]
Thanks for filing this issue!

I admit I am quite lost as to what it's about though. There's no description aside from the links. The linked issues are about Eclipse, Java and Visual Studio Code. This repository is about .NET, container images and s2i. I feel like you wanted to report this issue elsewhere, but I am not familiar enough with Java or Visual Studio Code to tell you where.

**Comment by max2max4u** [comment]
Hello. Please send a link with an new password
