### ISSUE TITLE
Add support for incremental builds

### ISSUE THREAD

**Issue by jerboaa** [redhat-developer/s2i-dotnetcore#37]
Source-to-image allows for [incremental builds](https://github.com/openshift/source-to-image#incremental-builds) which we should support. Something along the lines of:
https://github.com/openshift-s2i/s2i-aspnet/blob/master/s2i/assemble
and
https://github.com/openshift-s2i/s2i-aspnet/blob/master/s2i/save-artifacts

**Comment by tmds** [comment]
This was implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/260.
