### ISSUE TITLE
How to add trusted CA certificate?

### ISSUE THREAD

**Issue by AndreasGey** [redhat-developer/s2i-dotnetcore#374]
I get an error on dotnet restore:

  Determining projects to restore...
/usr/lib64/dotnet/sdk/5.0.206/NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/opt/app-root/src/ConverterServiceWebApi/ConverterServiceWebApi.csproj]
/usr/lib64/dotnet/sdk/5.0.206/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/opt/app-root/src/ConverterServiceWebApi/ConverterServiceWebApi.csproj]
/usr/lib64/dotnet/sdk/5.0.206/NuGet.targets(131,5): error :   The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot [/opt/app-root/src/ConverterServiceWebApi/ConverterServiceWebApi.csproj]
Error during restore

This is caused by the custom proxy ca certificate that we use.
How can i add this certificate to the trusted root ca certificates?
I added the certificate already to the "build trusted ca" like documented here: https://docs.openshift.com/container-platform/4.8/cicd/builds/setting-up-trusted-ca.html.

**Comment by tmds** [comment]
Have you tried using the `DOTNET_SSL_DIRS` envvar? https://github.com/redhat-developer/s2i-dotnetcore/blob/master/5.0/runtime/README.md#environment-variables
