### ISSUE TITLE
Remove DEV_MODE feature

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#386]
This is a feature we've implemented with @mickaelistria and @rgrunber 4 years back for https://github.com/redhat-developer/s2i-dotnetcore/issues/116.

I checked with them, and based on their feedback there seems to be no more IDEs that depend on this feature.

I propose we remove the it for the up-coming 6.0 release.

@aslicerh @omajid is this ok for you?

**Comment by aslicerh** [comment]
I'm ok with this.

**Comment by omajid** [comment]
> I propose we remove the it for the up-coming 6.0 release.

That seems safe to do. :+1: from me. I was worried about breaking existing users, but those wouldn't be using 6.0.

**Comment by tmds** [comment]
Fixed by https://github.com/redhat-developer/s2i-dotnetcore/pull/387.
