### ISSUE TITLE
Change default CMD to a shell.

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#390]
I ran into an issue when swapping between Microsoft and Red Hat .NET images.

The issue comes from Microsoft images running a shell as their default CMD, and our images printing out s2i usage.

```
$ podman run -ti mcr.microsoft.com/dotnet/sdk:5.0
root@2789824aaa41:/#
```
vs
```
$ podman run -ti registry.redhat.io/rhel8/dotnet-50
This is a S2I .Net rhel base image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

sudo s2i build https://github.com/redhat-developer/s2i-dotnetcore-ex.git --context-dir=app --ref=dotnet-5.0 dotnet/dotnet-50-rhel7 dotnet-sample-app

You can then run the resulting image via:
sudo docker run -p 8080:8080 dotnet-sample-app
```

I'd like to change our images to use a shell also.
Besides it behaving the same as Microsoft images, I think it is also more expected/useful behavior than printing the s2i usage.

I checked with @adambkaplan and @bparees and they have no concerns with this change.

Because it is a breaking change, I propose we make it as part of our next update of the .NET 6 containers which we've just released.
I'd keep the other versions unchanged.

@omajid @aslicerh are you ok with this change?

**Comment by omajid** [comment]
I am not comfortable with making a breaking change to 6.0 now (post GA release).

**Comment by tmds** [comment]
by this I mean:

> it is super unlikely we'll break someone

The commands in the top comment show the full change: instead of printing s2i usage, the user will get a shell.

None of the OpenShift/s2i tooling relies on this being the default behavior of an image.

> the benefits are real.

It behaves the same as Microsoft's image.

The image can be used directly.

For someone that does not know about s2i, the usage instructions can even be confusing.

**Comment by bparees** [comment]
> The commands in the top comment show the full change: instead of printing s2i usage (informative), the user will get a shell (functional).
> None of the OpenShift/s2i tooling relies on this being the default behavior of an image.

+1, while technically maybe it's a breaking change, it's pretty hard to imagine who would get broken by this change because it means you have a workflow where you expect the image, when run by default, to print out usage and exit for some reason, and that when instead it gives you a shell, it's going to break your expectations.

while i can conceive of a scripted/automated scenario where that might happen, i have a hard time conceiving of why someone would have implemented such a scenario.

**Comment by omajid** [comment]
Thanks for clearing this up. If this doesn't break existing users in any meaningful way, then I am okay with this change.
