### ISSUE TITLE
Could not execute because the application was not found or a compatible .NET SDK is not installed.

### ISSUE THREAD

**Issue by ardacetinkaya** [redhat-developer/s2i-dotnetcore#398]
I am try to build my app as below with [ubi8/dotnet-50 image](https://catalog.redhat.com/software/containers/rhel8/dotnet-50/5f6278e017452dea0fe47bae)
```
s2i build Product\ registry.access.redhat.com/ubi8/dotnet-50@sha256:f2e95baa5f3ee5ecc1fb3af8ac6029af818614c46d00de5cb1faabf3411a31b7 somename
```

In my repo, I have global.json file in solution with SDK version .NET 5 SDK 5.0.404. It seems that the image's .NET 5 SDK is 5.0.210

So how can I build my project without changing my global.json file? Also is there an SDK version in somewhere?

```
I0203 12:16:58.558189   43440 sti.go:711] ---> Installing application source...
I0203 12:16:58.572956   43440 sti.go:715] Could not execute because the application was not found or a compatible .NET SDK is not installed.
I0203 12:16:58.572956   43440 sti.go:715] Possible reasons for this include:
I0203 12:16:58.572956   43440 sti.go:715]   * You intended to execute a .NET program:
I0203 12:16:58.573466   43440 sti.go:715]       The application '--version' does not exist.
I0203 12:16:58.573511   43440 sti.go:715]   * You intended to execute a .NET SDK command:
I0203 12:16:58.573511   43440 sti.go:715]       A compatible installed .NET SDK for global.json version [5.0.404] from [/opt/app-root/src/global.json] was not found.
I0203 12:16:58.573511   43440 sti.go:715]       Install the [5.0.404] .NET SDK or update [/opt/app-root/src/global.json] with an installed .NET SDK:
I0203 12:16:58.572956   43440 sti.go:711] Using SDK:         5.0.210 [/usr/lib64/dotnet/sdk]
```

**Comment by tmds** [comment]
> So how can I build my project without changing my global.json file?

There is no specific feature that allows you to do this. You could add a custom assemble script to your repo, which removes the `global.json` file and then calls the base assemble script.

I wonder: if you are going to ignore `global.json` when you build the app, why do you want to keep the file in the source repo?

> Also is there an SDK version in somewhere?

There is no variable that exposes the SDK version. You can get it by running `dotnet --version` in a container.

**Comment by ardacetinkaya** [comment]
@tmds Thanks for a quick reply. 

I don't want(or can't) to change/ignore my ```global.json```
It seems that current builder image(dotnet-50) seems not have a support for .NET 5 SDK 5.0.404 and it has support just for 5.0.210...

It seems that it's possible to run the build if I am able to downgrade .NET 5 SDK version to 5.0.210 but I can't do that due to some other requirements.

**Comment by tmds** [comment]
> seems not have a support for .NET 5 SDK 5.0.404 and it has support just for 5.0.210...

Yes, .NET has multiple SDK 'feature bands' which are both supported at the same time. 5.0.2xx, and 5.0.4yy. We only provide one.

Can you use a custom `assemble` script?

You need to add a script in your source repo at `.s2i/bin/assemble`:
```sh
#!/bin/bash

set -ex

# Remove NuGet.Config file.
pushd /tmp/src
rm NuGet.Config
popd

# call base assemble script
$STI_SCRIPTS_PATH/assemble
```

**Comment by ardacetinkaya** [comment]
Thanks a lot. I will check this; but is there a specific reason not have another image for SDK 5.0.404? Or any plan to have in near future? If you also have ideas about these, it would be nice to know.

And within assemble file, I think just installing the SDK 5.0.404 would be enough, right?

**Comment by tmds** [comment]
> Thanks a lot. I will check this; but is there a specific reason not have another image for SDK 5.0.404? Or any plan to have in near future? If you also have ideas about these, it would be nice to know.

We only provide a single version band for the SDK. For maximum compatibility we are sticking to the oldest, but we may change that in the future. It depends on what compatibility is guaranteed between bands, and how well moving across feature bands is supported by [source-build](https://github.com/dotnet/source-build).

> So what is the best approach in here?

I recommend you remove the `NuGet.config` file from the sources in the `assemble` script.

> I think DOTNET_SDK_VERSION is now required in these cases. Any possibility to bring it back :)

Since we only ship a single SDK version band, we no removed `DOTNET_SDK_VERSION` and won't bring it back.

**Comment by tmds** [comment]
I'm going to close this. The issue can be solved by removing the `NuGet.Config` file in source control, or in the `assemble` script.

**Comment by ardacetinkaya** [comment]
No, this issue can not be solved by removing the Nuget.config file. 

Because currently used image "ubi8/dotnet-50" does not have support for SDK 5.0.404, this is the main reason for this issue.

And trying to install required SDK with assemble does not work because of some permission issues.

I think the only valid and solid way to solve this issue to have supported "ubi8/dotnet-50" image for SDK 5.0.404

**Comment by tmds** [comment]
We only support installing .NET versions that are available through the package manager.

If you need a specific feature that is only in the 5.0.4xx SDK, please create a ticket with Red Hat.

Otherwise the recommendation is to remove `global.json` (`NuGet.Config` was a typo).
