### ISSUE TITLE
Should the build script set `FORCE` to `true` by default?

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore#399]
I wasted quite a bit of time today because my changes to the assemble scripts were not showing up. It turns out we only build things once, and never again if the containers exist.

We can fix that by setting `FORCE` to `true`:

https://github.com/redhat-developer/s2i-dotnetcore/blob/f45a2e59a023dc983f513410582893dbafd5d727/build.sh#L41

That would mean that a simple execution of ./build.sh would do extra work, but it would ensure that stale assets are never used. Users can still optimize their workflow by setting `FORCE` to `false`.

**Comment by aslicerh** [comment]
I don't have a particular preference either way.

**Comment by tmds** [comment]
I don't ever set this flag, I manually delete the images if I want to rebuild them.

**Comment by tmds** [comment]
Closing old issue.
