### ISSUE TITLE
NPM config to set login parameter

### ISSUE THREAD

**Issue by ascholz** [redhat-developer/s2i-dotnetcore#410]
Question wouldn't it make sense to specify for NPM a login parameter as well? Because some registry need a login possibility. For Example we have an Artifactory server that needs authentication. 

https://stackoverflow.com/questions/23460980/how-to-set-npm-credentials-using-npm-login-without-reading-from-stdin

**Comment by tmds** [comment]
I'm going to close this. We can consider it if s2i-nodejs has this parameter.
