### ISSUE TITLE
DotnetCore S2i push image to Jfrog Artifactory

### ISSUE THREAD

**Issue by codeground123** [redhat-developer/s2i-dotnetcore#416]
Hi 

So far we are able to build the image using S2i and are looking for below to achieve 

- 
- How can we push the build image to Private registry(jfrog artifactory ?)
- How to rollback to previous build ?  Should we again merge the code to Master and then trigger the build again ?
- We are triggering the s2i build using "OC start-build" command from Azure Devops, How could I see if the build is successful ?

Dint want to create separate threads for the above three questions so posting in the same questions

Please share your thoughts on this

**Comment by tmds** [comment]
These questions are not .NET specific.
You should ask them to who is supporting you in your OpenShift deployment.
