### ISSUE TITLE
Permission handling problem in /tmp/.dotnet

### ISSUE THREAD

**Issue by mkeuschn** [redhat-developer/s2i-dotnetcore#437]
After the last update the permissions of the session folder has changed.

Access permissions before update:
```
sh-4.4$ ls -la
total 0
drwxrwxrwx. 1 default root 22 Dec 13 20:51 .
drwxrwxrwx. 1 default root 17 Dec 13 20:51 ..
drwxrwxrwx. 1 default root  6 Dec 19 14:27 session1
```
Access permissions after update:
```
sh-4.4$ ls -la
total 0
drwxrwxrwt. 3 default root  22 Dec 16 11:04 .
drwxrwxrwx. 3 default root  17 Dec 16 11:04 ..
drwx------. 2 default root 104 Dec 16 11:07 session1
```

In WSL(Ubuntu) the permissions are:
```
/tmp/.dotnet/shm$ ls -la
total 12
drwxrwxrwt 3 bugs bugs 4096 Dec 19 15:18 .
drwxrwxrwx 3 bugs bugs 4096 Dec 19 15:18 ..
drwx------ 2 bugs bugs 4096 Dec 19 15:18 session82
```
During the build an session folder is created by the default user. In app run mode another user is used. (Maybe the tmp folder should be deleted at the end of the build?)

This caused an error for some operations in c# (e.g. Create Mutex).

Sample Project: https://github.com/mkeuschn/named-mutex

SO: https://stackoverflow.com/questions/74823773/create-mutex-throws-error-the-system-cannot-open-the-device-or-file-specified

## Workaround

I have added my own assemble file to delete the session folders.

```
#!/bin/bash
echo "Before assembling"

/usr/libexec/s2i/assemble
rc=$?

if [ $rc -eq 0 ]; then
    echo "After successful assembling"
	echo "Delete /tmp/.dotnet/shm/*"
	rm -rf /tmp/.dotnet/shm/*
else
    echo "After failed assembling"
fi

exit $rc
```
Now it is working as expected.

**Comment by tmds** [comment]
Thanks for reporting the issue, and the clear report.

> I have added my own assemble file to delete the session folders.

Do you want to make a PR that adds this to the default `assemble` file?
If not, I will look into making the change.

cc @aslicerh @omajid

**Comment by mkeuschn** [comment]
> Thanks for reporting the issue, and the clear report.
> 
> > I have added my own assemble file to delete the session folders.
> 
> Do you want to make a PR that adds this to the default `assemble` file? If not, I will look into making the change.
> 
> cc @aslicerh @omajid

I have created a pull request.

**Comment by tmds** [comment]
Fixed by https://github.com/redhat-developer/s2i-dotnetcore/pull/439.

**Comment by tmds** [comment]
fyi, the changed that cause this permission issue is being reverted: https://github.com/dotnet/runtime/pull/90342.
