### ISSUE TITLE
Rename default branch to 'main'

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#449]
Following naming guidelines, we will rename the default branch of this repository from `master` to `main`.

There are many links to the `master` branch.
We will keep the branch around for some time after all .NET versions defined are EOL.
The .NET 6 version goes EOL in Nov 2024, and we will remove `master` one year after: in November 2025.

The `master` branch will be made read-only when the `main` branch is added.

Any automations that pull from the `master` branch need to be updated to the `main` branch.
This includes detecting new versions of .NET by retrieving the `dotnet_imagestreams*.json` files.
The next version of .NET (.NET 8) will be added in November 2023.

Unless there is feedback we shouldn't do this, I will add the `main` branch next week.

@bparees @yselkowitz @adambkaplan fyi

cc @omajid @aslicerh

**Comment by adambkaplan** [comment]
cc @cdaley @dperaza4dustbit

**Comment by tmds** [comment]
I've added the `main` branch, and set it to be the default.
The `master` branch is now read-only.

**Comment by yselkowitz** [comment]
https://github.com/openshift/library/blob/master/official.yaml#L874-L900 and https://github.com/openshift/library/blob/master/community.yaml#L170-L176 need to be updated accordingly

**Comment by tmds** [comment]
https://github.com/openshift/library/pull/344 updates the library.

I'm going to close this as the main upstream work is done.
