### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#45]
There are no tags in this repository which match the released docker image tags. Can we add these?

For the 10 image, there are tags: 1.0-2, 1.0-8, 1.0-10, 1.0-12. What is the suffix used here?

**Comment by jerboaa** [comment]
I suppose we can add them. There is going to be many tags, though. Not sure what you are asking, with `What is the suffix used here?`. Can you clarify, please. Which suffix exactly?

**Comment by tmds** [comment]
> Can you clarify, please. Which suffix exactly?

The -2, -8, -10, -12. Why is there no -3, -4, ...?

**Comment by jerboaa** [comment]
It has something to do with internal things. The convention is that there is `<version>-<release>` similar to RPMs. Some releases didn't work and did not get released. Releases have to be unique. For every rebuild the release has to be bumped. Again, internal things :)

**Comment by tmds** [comment]
@jerboaa it looks like we're not adding these tags, so I'm closing this issue.
