### ISSUE TITLE
[.NET 8] (maybe) remove nss_wrapper

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#458]
The `nss_wrapper` is used to fake a user for the random uid that is used by OpenShift when running the image.

OpenShift 4 does not require this, as the user will be automagically added to `/etc/passwd`.

Openshift 3 requires the wrapper. OpenShift 3 is now past the 'Maintenance Support' phase, and in the final phase 'Extended Life' phase until June 2024.

Without the wrapper on OpenShift 3, a .NET application will work. The observable side-effect is the `Environment.UserName` will return an empty string.

We can remove the `nss_wrapper` with the .NET 8 images and accept the `UserName` side-effect when those images are used on OpenShift 3.11.
Or we wait until the .NET 9 images to remove the wrapper.

@omajid @aslicerh what do you think?

**Comment by aslicerh** [comment]
Personally, I think it is fine to remove it.

OpenShift 3 is for maintenance, not new development, and .NET 8 would, in my perspective, be 'new development' if we were making decisions specifically to create support for it, at the detriment of other use cases.

That said, maybe we should also figure out what kind of work around we could suggest should someone have an issue with this?

**Comment by tmds** [comment]
We don't expect issues except what was mentioned in the opening comment: `Environment.UserName` returning an empty string on OpenShift 3.11.
