### ISSUE TITLE
Specify dotnet configuration for dotnet test

### ISSUE THREAD

**Issue by LvanLeeuwen** [redhat-developer/s2i-dotnetcore#462]
When specifying tests to run using DOTNET_TEST_PROJECTS they're by default executed with configuration=Debug while DOTNET_CONFIGURATION might be set to Release. Can you please also use the specified DOTNET_CONFIGURATION for the dotnet test command?

**Comment by tmds** [comment]
> they're by default executed with configuration=Debug

For backwards compat we probably want to keep this behavior.
We can add another envvar that controls the configuration for tests (`DOTNET_TEST_CONFIGURATION`).

Are you using .NET 6, .NET 7, or both?

cc @omajid @aslicerh

**Comment by LvanLeeuwen** [comment]
That sounds like a perfect solution! We're currently using .NET 6 and we'll move to .NET 8 after its official release.

**Comment by aslicerh** [comment]
The PR for this change has been merged. It should show up in the official images with the next .NET monthly release.
