### ISSUE TITLE
ubi9-minimal based images for dotnet 8 runtime

### ISSUE THREAD

**Issue by slowtick** [redhat-developer/s2i-dotnetcore#484]
Hi Team,

Thank you for making ubi8/dotnet-80-runtime available.

Is there a ubi9/dotnet-80-runtime build in plan?

**Comment by omajid** [comment]
Thanks for filing this issue!

We don't have any plans at this moment, but that can change.

Can you help us understand the motivation for ubi9-based .NET container images? Is there something missing in UBI8? Is there some feature in UBI 9 that you are looking for?

**Comment by slowtick** [comment]
Looking for base image for porting a dotnet service to in OCP, I see ubi8/dotnet-80-runtime will suit our case & technically we should be okay with ubi8.

We currently run several ubi9/nodejs-20-minimal and ubi9/python-311 based containers. So were interested in knowing if ubi9 series for dotnet is in pipeline.

Thank you for confirmation. We will proceed with ubi8/dotnet-80-runtime for now as it is good for our use case.
