### ISSUE TITLE
Remove support for DOTNET_SSL_DIRS [9.0]

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#491]
Since .NET 8 we print a message to users of `DOTNET_SSL_DIRS` to use `SSL_CERT_DIR` instead.
```
warn: DOTNET_SSL_DIRS is deprecated. Please use SSL_CERT_DIR instead.
```
`DOTNET_SSL_DIRS` is a custom feature of our images, while `SSL_CERT_DIR` is a well-known OpenSSL envvar.
Since .NET 8, .NET supports multiple directories for `SSL_CERT_DIR` which enables using it as an alternative to `DOTNET_SSL_DIRS`.

This issue is for removing `DOTNET_SSL_DIRS` support in favor of `SSL_CERT_DIR`.

cc @omajid @aslicerh

**Comment by aslicerh** [comment]
I think that's a fine change.

**Comment by omajid** [comment]
Sounds good to me.

To ease migration, could we make sure we document/reference the syntax for specifying multiple-directories via SSL_CERT_DIR?

**Comment by tmds** [comment]
> To ease migration, could we make sure we document/reference the syntax for specifying multiple-directories via SSL_CERT_DIR?

We have this in the README:

https://github.com/redhat-developer/s2i-dotnetcore/blob/a0c7ee12d0c723785e8756b359a8eb2b24833019/8.0/runtime/README.md?plain=1#L82-L92

**Comment by omajid** [comment]
Thanks, I don't know how I missed that. That works for me.
