### ISSUE TITLE
Add dotnet template

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#56]
Similar to https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/master/templates/aspnet-s2i-template.json, but different...

- [ ] rename aspnet to dotnet

aspnet refers to the open source microsoft webstack. There are other popular webstacks like nancy (http://nancyfx.org/). s2i-dotnetcore is not 'aspnet' specific.

- [ ] add parameters for all s2i-dotnetcore environment variables

The names of these parameters match the environment names exactly.

- [ ] Store the template in this repo

The template is versioned with the rest of the s2i-dotnetcore repo.

@jerboaa @omajid what's do you think?

**Comment by jerboaa** [comment]
+1. We should also massage the template to work independent of which dotnet core builder image is being used. Currently, the `dotnetcore-1.1` and `dotnetcore-1.0` branches have slightly different templates. This should be possible to achieve with parameters.
