### ISSUE TITLE
Support runtime image with store

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#86]
As part of the assemble for 2.0 we currently override all stores by specifying `/p:TargetManifestFiles=`.

We should support the case where a user wants to create its own runtime image that includes a store. This may be the ASP.NET Core runtime store. It can also be a custom store (which can be meaningful in large deployments).

Instead of setting `TargetManifestFiles`, we can add a new property `DOTNET_ASPNET_STORE` that defaults to `false` and is passed to the publish command to set the `PublishWithAspNetCoreTargetManifest` property.

CC @omajid @jerboaa @aslicerh

**Comment by omajid** [comment]
How do custom stores and the ASP.NET package store interact? If PublishWithAspNetCoreTargetManifest is false, will a custom store be used? How would a user add a custom store to the runtime?

**Comment by botfathr** [comment]
@omajid

**Comment by botfathr** [comment]
#82

**Comment by tmds** [comment]
> How do custom stores and the ASP.NET package store interact?

It's possible to install several store.

> If PublishWithAspNetCoreTargetManifest is false, will a custom store be used?

This property is specific to the AspNetCore.All meta package which does this:
```xml
    <PublishWithAspNetCoreTargetManifest Condition="'$(PublishWithAspNetCoreTargetManifest)'=='' and '$(RuntimeIdentifier)'=='' and '$(RuntimeIdentifiers)'=='' and '$(PublishableProject)'=='true'">true</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishWithAspNetCoreTargetManifest)'=='true'">
    <TargetManifestFiles>$(TargetManifestFiles);$(MSBuildThisFileDirectory)manifest.win7-x64.xml;$(MSBuildThisFileDirectory)manifest.win7-x86.xml;$(MSBuildThisFileDirectory)manifest.osx-x64.xml;$(MSBuildThisFileDirectory)manifest.linux-x64.xml</TargetManifestFiles>
  </PropertyGroup>
```

The first section enables the store when the project isn't published for a specific rid.
The second section adds manifest included in the package to the `TargetManifestFiles` property.

> How would a user add a custom store to the runtime?

This is by creating a custom runtime image (e.g. based on our runtime image). As part of the image Dockerfile, the `dotnet store` command can be used to add packages to the store. Roughly, this command accepts a csproj file and takes it's dependencies, crossgens (= pre-jit) them for the local machine and puts them in the store.

Then the user can use our sdk image and use the output with his custom runtime image.

**Comment by tmds** [comment]
Implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/90
