### ISSUE TITLE
Dotnet runtime image has default root user

### ISSUE THREAD

**Issue by jerboaa** [redhat-developer/s2i-dotnetcore#87]
Steps to reproduce:

    sudo docker run -ti --rm --entrypoint=/bin/bash dotnet/dotnet-20-rhel7-runtime -c 'whoami'
    root

Should be: `default`

The builder image is fine:

    sudo docker run -ti --rm --entrypoint=/bin/bash dotnet/dotnet-20-rhel7 -c 'whoami'
    default

We are likely missing a: `User 1001`

**Comment by jerboaa** [comment]
@aslicerh Please take a look when you get a chance.

**Comment by jerboaa** [comment]
`generate_container_user` and related hooks should also be present in the runtime image.

**Comment by aslicerh** [comment]
`generate_container_user` only seems to get called from the s2i run script. Without those being present in the runtime image, how does openshift know to use it?

**Comment by jerboaa** [comment]
How is the built binary being launched in the runtime image, then? `generate_container_user` should be present in the runtime image.

**Comment by aslicerh** [comment]
When you build off of the runtime image you need to specify a CMD in the dockerfile for launching your app.

If you use the build image (via s2i) to generate the binaries that you then want to run on the runtime image, then the build image ends up having it and the only thing necessary for execution should be in the publish folder (which can be executed by the generates s2i_run script, which doesn't call the s2i run script either).

**Comment by jerboaa** [comment]
> When you build off of the runtime image you need to specify a CMD in the dockerfile for launching your app.

OK. Documentation/example for this should have `source /opt/app-root/etc/generate_container_user` in it prior launching the app.

> If you use the build image (via s2i) to generate the binaries that you then want to run on the runtime image, then the build image ends up having it and the only thing necessary for execution should be in the publish folder (which can be executed by the generates s2i_run script, which doesn't call the s2i run script either).

Yes, I'm assuming our s2i builder was used to build the binaries.

In 1.0/1.1 the s2i/bin/run script is invoked when running the application. That script has `source /opt/app-root/etc/generate_container_user` as the [first line](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.1/s2i/bin/run#L2) and then, if DOTNET_PUBLISH==true calls DOTNET_RUN_SCRIPT==/opt/app-root/publish/s2i_run See https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.1/Dockerfile.rhel7#L14

One way to go about this would be to:

1. Make sure the runtime image has `/opt/app-root/etc/generate_container_user` installed
2. Modify `/opt/app-root/publish/s2i_run` to source `generate_container_user`.
3. Suggest to call `/opt/app-root/publish/s2i_run` via CMD in Dockerfile

Thoughts?

**Comment by aslicerh** [comment]
> One way to go about this would be to:
> 1. Make sure the runtime image has /opt/app-root/etc/generate_container_user installed
> 2. Modify /opt/app-root/publish/s2i_run to source generate_container_user.
> 3. Suggest to call /opt/app-root/publish/s2i_run via CMD in Dockerfile
>
> Thoughts?

1 is already done in the newest PR. 2 sounds like a good idea.

Can you clarify what you mean by 3? Do you mean in the examples, in the README, or with some default usage script setup in the runtime image (or some combination of these)?

**Comment by jerboaa** [comment]
@aslicerh You said:
> When you build off of the runtime image you need to specify a CMD in the dockerfile for launching your app.

I assumed you meant a CMD in an inline Dockerfile, for example in a template which produces a runnable image from the builder and runs it with the runtime image. The documentation part for this needs to suggest 3 :)

Does that make sense?

**Comment by jerboaa** [comment]
[cibuild]

**Comment by aslicerh** [comment]
@jerboaa 
Yeah, that was what I meant, and that makes sense.

**Comment by tmds** [comment]
@aslicerh @jerboaa I think this is implemented in https://github.com/redhat-developer/s2i-dotnetcore/pull/88, so closing. If not, please re-open.
