### ISSUE TITLE
Use of dotnet:latest tag

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#89]
I wonder if we should remove the dotnet:latest from our image streams.

1. Latest can break builds.
E.g. when latest moved from 1.0 to 1.1, all 1.0 using latest would break.
Versioning rules have been changed for .NET Core 2.
Now when latest moves from 2.x to 3.x things will break.

2. Asides from us breaking the apps by moving latest, users need to use a version that is compatible with their .NET Core application. This isn't necessarily latest. So they know explicitly what version they'd like.

(Note there is a use-case for 'latest 2x' as this allows users to stay on a supported compatible version. We can consider that when we do 2.1.)

Feel free to give some feedback. If you are fine with removing latest, a thumbs up on the issue is enough.

CC @omajid @jerboaa @aslicerh @bparees

**Comment by bparees** [comment]
i think that's fine.  latest is intended as a convenience for someone who's doing a one-off and understand the potential breakage that can occur and just want whatever the latest is right now.  Not having it (and thus helping users avoid trouble) should be fine.

**Comment by bparees** [comment]
but i should note that all our other imagestreams do provide a latest, so you may raise some consistency questions from users.

**Comment by jerboaa** [comment]
I agree with @bparees. Users of `dotnet:latest` might be well aware that it's risky. For sake of consistency with other language stacks I'd suggest to keep it.

**Comment by tmds** [comment]
My concern is for users of `dotnet:latest` which are not aware it is risky.
Closing the issue since there is some desire to have the latest for consistency.
