### ISSUE TITLE
runtime image does not have an entrypoint

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#95]
To use the runtime image, you can do this:
```
FROM registry.access.redhat.com/dotnet20-runtime-rhel7

ADD bin/Release/netcoreapp2.0/rhel.7-x64/publish/. .

CMD ["scl", "enable", "rh-dotnet20", "--", "dotnet", "couchbase_demo.dll"]
```
It would be nicer without the scl enable.
We can probably handle this via an ENTRYPOINT.
This should also call generate_container_user.

The entrypoint could also check for the s2i_run script and invoke that when there are no arguments. Then the user doesn't need to handle this for a s2i build into a runtime image.

**Comment by tmds** [comment]
Andrew, can you look at this? I will be on pto for the next weeks.
CC @jerboaa @omajid

**Comment by jerboaa** [comment]
Thanks for filing the bug @tmds

**Comment by jerboaa** [comment]
The reason why the "scl enable" is needed because there is no defined entrypoint which goes through bash. For example `CMD ['bash', '-c', 'dotnet couchbase_demo.dll'] works fine. The builder has an [explicit entrypoint](https://github.com/redhat-developer/s2i-dotnetcore/blob/2.0-dev/2.0/build/Dockerfile.rhel7#L62) that goes through bash. Perhaps we should move those bits from the builder image to the runtime image.

@aslicerh Thoughts?

**Comment by aslicerh** [comment]
@jerboaa That sounds like a good idea. I'm at a good stopping point in what I'm working on, so I'll have a PR for this up next.

**Comment by jerboaa** [comment]
Fixed with PR #96.

**Comment by tmds** [comment]
@jerboaa @aslicerh the PR doesn't include

> This should also call generate_container_user.

Any thoughts on including this in the entrypoint script?

**Comment by aslicerh** [comment]
@tmds I was going to discuss that with you when you came back. The generate_container_user script adds an entry into the nss passwd file every time it is run. If you add it to the ENTRYPOINT, then each time the same container is run it will keep adding more and more duplicate entries.

We should either find a way to add it to the assembly of the container, or we need to change/create the script to check if the entry already exists and add it if it doesn't.
